#include "src/game/envfx_snow.h"

const GeoLayout mad_piano_geo[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_SHADOW(0, 150, 100),
		GEO_OPEN_NODE(),
			GEO_SCALE(0, 16384),
			GEO_OPEN_NODE(),
				GEO_ANIMATED_PART(1, 0, 0, 0, NULL),
				GEO_OPEN_NODE(),
					GEO_ANIMATED_PART(1, 0, 0, 0, mad_piano_000_offset_mesh),
					GEO_OPEN_NODE(),
						GEO_ANIMATED_PART(1, -141, -546, 218, NULL),
						GEO_OPEN_NODE(),
							GEO_ANIMATED_PART(1, 0, 0, 0, mad_piano_000_offset_002_mesh),
						GEO_CLOSE_NODE(),
					GEO_CLOSE_NODE(),
				GEO_CLOSE_NODE(),
			GEO_CLOSE_NODE(),
		GEO_CLOSE_NODE(),
		GEO_DISPLAY_LIST(0, mad_piano_material_revert_render_settings),
		GEO_DISPLAY_LIST(1, mad_piano_material_revert_render_settings),
		GEO_DISPLAY_LIST(2, mad_piano_material_revert_render_settings),
		GEO_DISPLAY_LIST(3, mad_piano_material_revert_render_settings),
		GEO_DISPLAY_LIST(4, mad_piano_material_revert_render_settings),
		GEO_DISPLAY_LIST(5, mad_piano_material_revert_render_settings),
		GEO_DISPLAY_LIST(6, mad_piano_material_revert_render_settings),
		GEO_DISPLAY_LIST(7, mad_piano_material_revert_render_settings),
	GEO_CLOSE_NODE(),
	GEO_END(),
};
