#include "src/game/envfx_snow.h"

const GeoLayout bub_geo[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_SCALE(0, 16384),
		GEO_OPEN_NODE(),
			GEO_ANIMATED_PART(1, -13, 0, 0, NULL),
			GEO_OPEN_NODE(),
				GEO_ANIMATED_PART(1, 0, 0, 0, bub_000_offset_mesh),
				GEO_OPEN_NODE(),
					GEO_ANIMATED_PART(1, 135, 0, 0, bub_000_offset_001_mesh),
					GEO_ANIMATED_PART(1, -33, -86, -35, NULL),
					GEO_OPEN_NODE(),
						GEO_ANIMATED_PART(1, 0, 0, 0, bub_000_offset_002_mesh),
					GEO_CLOSE_NODE(),
					GEO_ANIMATED_PART(1, -34, 71, -36, NULL),
					GEO_OPEN_NODE(),
						GEO_ANIMATED_PART(1, 0, 0, 0, bub_000_offset_003_mesh),
					GEO_CLOSE_NODE(),
				GEO_CLOSE_NODE(),
			GEO_CLOSE_NODE(),
		GEO_CLOSE_NODE(),
		GEO_DISPLAY_LIST(0, bub_material_revert_render_settings),
		GEO_DISPLAY_LIST(1, bub_material_revert_render_settings),
		GEO_DISPLAY_LIST(2, bub_material_revert_render_settings),
		GEO_DISPLAY_LIST(3, bub_material_revert_render_settings),
		GEO_DISPLAY_LIST(4, bub_material_revert_render_settings),
		GEO_DISPLAY_LIST(5, bub_material_revert_render_settings),
		GEO_DISPLAY_LIST(6, bub_material_revert_render_settings),
		GEO_DISPLAY_LIST(7, bub_material_revert_render_settings),
	GEO_CLOSE_NODE(),
	GEO_END(),
};
