#include "src/game/envfx_snow.h"

const GeoLayout flyguy_geo[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_SHADOW(0, 150, 100),
		GEO_OPEN_NODE(),
			GEO_SCALE(0, 16384),
			GEO_OPEN_NODE(),
				GEO_ANIMATED_PART(1, 0, 0, 0, NULL),
				GEO_OPEN_NODE(),
					GEO_ANIMATED_PART(1, 0, 0, 0, flyguy_000_offset_mesh),
					GEO_OPEN_NODE(),
						GEO_ANIMATED_PART(1, -45, -20, -55, NULL),
						GEO_OPEN_NODE(),
							GEO_ANIMATED_PART(1, 0, 0, 0, flyguy_000_offset_002_mesh),
						GEO_CLOSE_NODE(),
						GEO_ANIMATED_PART(1, -45, -20, 55, NULL),
						GEO_OPEN_NODE(),
							GEO_ANIMATED_PART(1, 0, 0, 0, flyguy_000_offset_003_mesh),
						GEO_CLOSE_NODE(),
						GEO_ANIMATED_PART(1, 250, 0, 0, NULL),
						GEO_OPEN_NODE(),
							GEO_ANIMATED_PART(5, 0, 0, 0, flyguy_000_offset_004_mesh),
							GEO_ANIMATED_PART(1, 0, 0, 0, NULL),
						GEO_CLOSE_NODE(),
					GEO_CLOSE_NODE(),
				GEO_CLOSE_NODE(),
			GEO_CLOSE_NODE(),
		GEO_CLOSE_NODE(),
		GEO_DISPLAY_LIST(0, flyguy_material_revert_render_settings),
		GEO_DISPLAY_LIST(1, flyguy_material_revert_render_settings),
		GEO_DISPLAY_LIST(2, flyguy_material_revert_render_settings),
		GEO_DISPLAY_LIST(3, flyguy_material_revert_render_settings),
		GEO_DISPLAY_LIST(4, flyguy_material_revert_render_settings),
		GEO_DISPLAY_LIST(5, flyguy_material_revert_render_settings),
		GEO_DISPLAY_LIST(6, flyguy_material_revert_render_settings),
		GEO_DISPLAY_LIST(7, flyguy_material_revert_render_settings),
	GEO_CLOSE_NODE(),
	GEO_END(),
};
