#include "src/game/envfx_snow.h"

const GeoLayout dorrie_geo[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_CULLING_RADIUS(1063830),
		GEO_OPEN_NODE(),
			GEO_SCALE(0, 16384),
			GEO_OPEN_NODE(),
				GEO_ANIMATED_PART(1, 0, 0, 0, NULL),
				GEO_OPEN_NODE(),
					GEO_ANIMATED_PART(1, 0, 0, 0, dorrie_000_offset_mesh),
					GEO_OPEN_NODE(),
						GEO_DISPLAY_LIST(1, dorrie_000_offset_001_skinned),
						GEO_ANIMATED_PART(1, 1295, 0, 0, dorrie_000_offset_001_mesh),
						GEO_OPEN_NODE(),
							GEO_DISPLAY_LIST(1, dorrie_000_offset_002_skinned),
							GEO_ANIMATED_PART(1, 916, 0, 0, dorrie_000_offset_002_mesh),
							GEO_OPEN_NODE(),
								GEO_DISPLAY_LIST(1, dorrie_000_offset_003_skinned),
								GEO_ANIMATED_PART(1, 874, 0, 0, dorrie_000_offset_003_mesh),
								GEO_OPEN_NODE(),
									GEO_DISPLAY_LIST(4, NULL),
									GEO_ANIMATED_PART(1, 30, 444, -6, NULL),
									GEO_OPEN_NODE(),
										GEO_ANIMATED_PART(1, 0, 0, 0, NULL),
									GEO_CLOSE_NODE(),
								GEO_CLOSE_NODE(),
							GEO_CLOSE_NODE(),
						GEO_CLOSE_NODE(),
						GEO_ANIMATED_PART(1, -893, -490, -6, NULL),
						GEO_OPEN_NODE(),
							GEO_ANIMATED_PART(1, 0, 0, 0, NULL),
							GEO_OPEN_NODE(),
								GEO_ANIMATED_PART(1, 1300, 0, 0, NULL),
							GEO_CLOSE_NODE(),
						GEO_CLOSE_NODE(),
						GEO_ANIMATED_PART(1, -1086, 91, -700, NULL),
						GEO_OPEN_NODE(),
							GEO_ANIMATED_PART(1, 0, 0, 0, dorrie_000_offset_007_mesh),
						GEO_CLOSE_NODE(),
						GEO_ANIMATED_PART(1, 902, 700, -785, NULL),
						GEO_OPEN_NODE(),
							GEO_ANIMATED_PART(1, 0, 0, 0, dorrie_000_offset_008_mesh),
						GEO_CLOSE_NODE(),
						GEO_ANIMATED_PART(1, -1086, 91, 698, NULL),
						GEO_OPEN_NODE(),
							GEO_ANIMATED_PART(1, 0, 0, 0, dorrie_000_offset_009_mesh),
						GEO_CLOSE_NODE(),
						GEO_ANIMATED_PART(1, 902, 700, 783, NULL),
						GEO_OPEN_NODE(),
							GEO_ANIMATED_PART(1, 0, 0, 0, dorrie_000_offset_010_mesh),
						GEO_CLOSE_NODE(),
					GEO_CLOSE_NODE(),
				GEO_CLOSE_NODE(),
			GEO_CLOSE_NODE(),
		GEO_CLOSE_NODE(),
		GEO_DISPLAY_LIST(0, dorrie_material_revert_render_settings),
		GEO_DISPLAY_LIST(1, dorrie_material_revert_render_settings),
		GEO_DISPLAY_LIST(2, dorrie_material_revert_render_settings),
		GEO_DISPLAY_LIST(3, dorrie_material_revert_render_settings),
		GEO_DISPLAY_LIST(4, dorrie_material_revert_render_settings),
		GEO_DISPLAY_LIST(5, dorrie_material_revert_render_settings),
		GEO_DISPLAY_LIST(6, dorrie_material_revert_render_settings),
		GEO_DISPLAY_LIST(7, dorrie_material_revert_render_settings),
	GEO_CLOSE_NODE(),
	GEO_END(),
};
