// 0x0D0000D8
const GeoLayout bowser_geo_0000D8[] = {
   GEO_SHADOW(SHADOW_CIRCLE_9_VERTS, 0x9B, 400),
   GEO_OPEN_NODE(),
      GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, bowser_root_mesh),
      GEO_OPEN_NODE(),
         GEO_ANIMATED_PART(LAYER_OPAQUE, -89, -2, -18, NULL),
         GEO_OPEN_NODE(),
            GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, NULL),
            GEO_OPEN_NODE(),
               GEO_ANIMATED_PART(LAYER_OPAQUE, 69, 0, 0, NULL),
               GEO_OPEN_NODE(),
                  GEO_ANIMATED_PART(LAYER_OPAQUE, 85, 0, 0, NULL),
                  GEO_OPEN_NODE(),
                     GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, bowser_000_offset_004_mesh),
                  GEO_CLOSE_NODE(),
                  GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, bowser_002_offset_mesh),
               GEO_CLOSE_NODE(),
            GEO_CLOSE_NODE(),
         GEO_CLOSE_NODE(),
         GEO_ANIMATED_PART(LAYER_OPAQUE, 0, -32, -112, NULL),
         GEO_OPEN_NODE(),
            GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, NULL),
            GEO_OPEN_NODE(),
               GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, bowser_000_offset_006_mesh),
               GEO_ASM(0, geo_update_body_rot_from_parent),
            GEO_CLOSE_NODE(),
         GEO_CLOSE_NODE(),
         GEO_ANIMATED_PART(LAYER_OPAQUE, 118, 67, 105, NULL),
         GEO_OPEN_NODE(),
            GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, NULL),
            GEO_OPEN_NODE(),
               GEO_ANIMATED_PART(LAYER_OPAQUE, 65, 0, 0, NULL),
               GEO_OPEN_NODE(),
                  GEO_ANIMATED_PART(LAYER_OPAQUE, 49, 0, 0, NULL),
                  GEO_OPEN_NODE(),
                     GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, bowser_000_offset_010_mesh),
                  GEO_CLOSE_NODE(),
                  GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, bowser_002_offset_002_mesh),
               GEO_CLOSE_NODE(),
               GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, bowser_002_offset_003_mesh),
            GEO_CLOSE_NODE(),
         GEO_CLOSE_NODE(),
         GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 136, 130, NULL),
         GEO_OPEN_NODE(),
            GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, NULL),
            GEO_OPEN_NODE(),
               GEO_ANIMATED_PART(LAYER_OPAQUE, 61, 0, 0, NULL),
               GEO_OPEN_NODE(),
                  GEO_ANIMATED_PART(LAYER_OPAQUE, -13, 258, 0, bowser_000_offset_013_mesh),
               GEO_CLOSE_NODE(),
               GEO_SWITCH_CASE(9, geo_switch_bowser_eyes),
               GEO_OPEN_NODE(),
                  GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, bowser_000_offset_014_mesh),
				  /*
                  GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, bowser_seg6_dl_060423A0),
                  GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, bowser_seg6_dl_060423F8),
                  GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, bowser_seg6_dl_06042450),
                  GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, bowser_seg6_dl_060424A8),
                  GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, bowser_seg6_dl_06042500),
                  GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, bowser_seg6_dl_06042558),
                  GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, bowser_seg6_dl_060425B0),
                  GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, bowser_seg6_dl_06042608),
				  */
               GEO_CLOSE_NODE(),
            GEO_CLOSE_NODE(),
         GEO_CLOSE_NODE(),
         GEO_ANIMATED_PART(LAYER_OPAQUE, -118, 67, 105, NULL),
         GEO_OPEN_NODE(),
            GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, NULL),
            GEO_OPEN_NODE(),
               GEO_ANIMATED_PART(LAYER_OPAQUE, 65, 0, 0, NULL),
               GEO_OPEN_NODE(),
                  GEO_ANIMATED_PART(LAYER_OPAQUE, 49, 0, 0, NULL),
                  GEO_OPEN_NODE(),
                     GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, bowser_000_offset_018_mesh),
                  GEO_CLOSE_NODE(),
                  GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, bowser_002_offset_004_mesh),
               GEO_CLOSE_NODE(),
               GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, bowser_002_offset_005_mesh),
            GEO_CLOSE_NODE(),
         GEO_CLOSE_NODE(),
         GEO_ANIMATED_PART(LAYER_OPAQUE, 89, -2, -18, NULL),
         GEO_OPEN_NODE(),
            GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, NULL),
            GEO_OPEN_NODE(),
               GEO_ANIMATED_PART(LAYER_OPAQUE, 69, 0, 0, NULL),
               GEO_OPEN_NODE(),
                  GEO_ANIMATED_PART(LAYER_OPAQUE, 85, 0, 0, NULL),
                  GEO_OPEN_NODE(),
                     GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, bowser_000_offset_022_mesh),
                  GEO_CLOSE_NODE(),
                  GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, bowser_002_offset_006_mesh),
               GEO_CLOSE_NODE(),
            GEO_CLOSE_NODE(),
         GEO_CLOSE_NODE(),
         GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, NULL),
         GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, NULL),
         GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, NULL),
         GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, NULL),
         GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, NULL),
         GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, NULL),
         GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, NULL),
         GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, NULL),
         GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, NULL),
      GEO_CLOSE_NODE(),
   GEO_CLOSE_NODE(),
   GEO_RETURN(),
};

// 0x0D000424
const GeoLayout bowser_geo_000424[] = {
   GEO_SHADOW(SHADOW_CIRCLE_9_VERTS, 0x9B, 400),
   GEO_OPEN_NODE(),
#ifdef VERSION_JP
      GEO_ANIMATED_PART(LAYER_TRANSPARENT, 0, 0, 0, bowser_root_mesh),
#else
      GEO_ANIMATED_PART(LAYER_TRANSPARENT, 0, 0, 0, bowser_root_mesh),
#endif
      GEO_OPEN_NODE(),
         GEO_ANIMATED_PART(LAYER_TRANSPARENT, -89, -2, -18, NULL),
         GEO_OPEN_NODE(),
            GEO_ANIMATED_PART(LAYER_TRANSPARENT, 0, 0, 0, NULL),
            GEO_OPEN_NODE(),
               GEO_ANIMATED_PART(LAYER_TRANSPARENT, 69, 0, 0, NULL),
               GEO_OPEN_NODE(),
                  GEO_ANIMATED_PART(LAYER_TRANSPARENT, 85, 0, 0, NULL),
                  GEO_OPEN_NODE(),
                     GEO_ANIMATED_PART(LAYER_TRANSPARENT, 0, 0, 0, bowser_000_offset_004_mesh),
                  GEO_CLOSE_NODE(),
                  GEO_ANIMATED_PART(LAYER_TRANSPARENT, 0, 0, 0, bowser_002_offset_mesh),
               GEO_CLOSE_NODE(),
            GEO_CLOSE_NODE(),
         GEO_CLOSE_NODE(),
         GEO_ANIMATED_PART(LAYER_TRANSPARENT, 0, -32, -112, NULL),
         GEO_OPEN_NODE(),
            GEO_ANIMATED_PART(LAYER_TRANSPARENT, 0, 0, 0, NULL),
            GEO_OPEN_NODE(),
               GEO_ANIMATED_PART(LAYER_TRANSPARENT, 0, 0, 0, bowser_000_offset_006_mesh),
               GEO_ASM(0, geo_update_body_rot_from_parent),
            GEO_CLOSE_NODE(),
         GEO_CLOSE_NODE(),
         GEO_ANIMATED_PART(LAYER_TRANSPARENT, 118, 67, 105, NULL),
         GEO_OPEN_NODE(),
            GEO_ANIMATED_PART(LAYER_TRANSPARENT, 0, 0, 0, NULL),
            GEO_OPEN_NODE(),
               GEO_ANIMATED_PART(LAYER_TRANSPARENT, 65, 0, 0, NULL),
               GEO_OPEN_NODE(),
                  GEO_ANIMATED_PART(LAYER_TRANSPARENT, 49, 0, 0, NULL),
                  GEO_OPEN_NODE(),
                     GEO_ANIMATED_PART(LAYER_TRANSPARENT, 0, 0, 0, bowser_000_offset_010_mesh),
                  GEO_CLOSE_NODE(),
                  GEO_ANIMATED_PART(LAYER_TRANSPARENT, 0, 0, 0, bowser_002_offset_002_mesh),
               GEO_CLOSE_NODE(),
               GEO_ANIMATED_PART(LAYER_TRANSPARENT, 0, 0, 0, bowser_002_offset_003_mesh),
            GEO_CLOSE_NODE(),
         GEO_CLOSE_NODE(),
         GEO_ANIMATED_PART(LAYER_TRANSPARENT, 0, 136, 130, NULL),
         GEO_OPEN_NODE(),
            GEO_ANIMATED_PART(LAYER_TRANSPARENT, 0, 0, 0, NULL),
            GEO_OPEN_NODE(),
               GEO_ANIMATED_PART(LAYER_TRANSPARENT, 61, 0, 0, NULL),
               GEO_OPEN_NODE(),
                  GEO_ANIMATED_PART(LAYER_TRANSPARENT, -13, 258, 0, bowser_000_offset_013_mesh),
               GEO_CLOSE_NODE(),
               GEO_SWITCH_CASE(9, geo_switch_bowser_eyes),
               GEO_OPEN_NODE(),
                  GEO_ANIMATED_PART(LAYER_TRANSPARENT, 0, 0, 0, bowser_000_offset_014_mesh),
				  /*
                  GEO_ANIMATED_PART(LAYER_TRANSPARENT, 0, 0, 0, bowser_seg6_dl_060423A0),
                  GEO_ANIMATED_PART(LAYER_TRANSPARENT, 0, 0, 0, bowser_seg6_dl_060423F8),
                  GEO_ANIMATED_PART(LAYER_TRANSPARENT, 0, 0, 0, bowser_seg6_dl_06042450),
                  GEO_ANIMATED_PART(LAYER_TRANSPARENT, 0, 0, 0, bowser_seg6_dl_060424A8),
                  GEO_ANIMATED_PART(LAYER_TRANSPARENT, 0, 0, 0, bowser_seg6_dl_06042500),
                  GEO_ANIMATED_PART(LAYER_TRANSPARENT, 0, 0, 0, bowser_seg6_dl_06042558),
                  GEO_ANIMATED_PART(LAYER_TRANSPARENT, 0, 0, 0, bowser_seg6_dl_060425B0),
                  GEO_ANIMATED_PART(LAYER_TRANSPARENT, 0, 0, 0, bowser_seg6_dl_06042608),
				  */
               GEO_CLOSE_NODE(),
            GEO_CLOSE_NODE(),
         GEO_CLOSE_NODE(),
         GEO_ANIMATED_PART(LAYER_TRANSPARENT, -118, 67, 105, NULL),
         GEO_OPEN_NODE(),
            GEO_ANIMATED_PART(LAYER_TRANSPARENT, 0, 0, 0, NULL),
            GEO_OPEN_NODE(),
               GEO_ANIMATED_PART(LAYER_TRANSPARENT, 65, 0, 0, NULL),
               GEO_OPEN_NODE(),
                  GEO_ANIMATED_PART(LAYER_TRANSPARENT, 49, 0, 0, NULL),
                  GEO_OPEN_NODE(),
                     GEO_ANIMATED_PART(LAYER_TRANSPARENT, 0, 0, 0, bowser_000_offset_018_mesh),
                  GEO_CLOSE_NODE(),
                  GEO_ANIMATED_PART(LAYER_TRANSPARENT, 0, 0, 0, bowser_002_offset_004_mesh),
               GEO_CLOSE_NODE(),
               GEO_ANIMATED_PART(LAYER_TRANSPARENT, 0, 0, 0, bowser_002_offset_005_mesh),
            GEO_CLOSE_NODE(),
         GEO_CLOSE_NODE(),
         GEO_ANIMATED_PART(LAYER_TRANSPARENT, 89, -2, -18, NULL),
         GEO_OPEN_NODE(),
            GEO_ANIMATED_PART(LAYER_TRANSPARENT, 0, 0, 0, NULL),
            GEO_OPEN_NODE(),
               GEO_ANIMATED_PART(LAYER_TRANSPARENT, 69, 0, 0, NULL),
               GEO_OPEN_NODE(),
                  GEO_ANIMATED_PART(LAYER_TRANSPARENT, 85, 0, 0, NULL),
                  GEO_OPEN_NODE(),
                     GEO_ANIMATED_PART(LAYER_TRANSPARENT, 0, 0, 0, bowser_000_offset_022_mesh),
                  GEO_CLOSE_NODE(),
#ifdef VERSION_JP
                  GEO_ANIMATED_PART(LAYER_TRANSPARENT, 0, 0, 0, bowser_002_offset_006_mesh),
#else
                  GEO_ANIMATED_PART(LAYER_TRANSPARENT, 0, 0, 0, bowser_002_offset_006_mesh),
#endif
               GEO_CLOSE_NODE(),
            GEO_CLOSE_NODE(),
         GEO_CLOSE_NODE(),
         GEO_ANIMATED_PART(LAYER_TRANSPARENT, 0, 0, 0, NULL),
         GEO_ANIMATED_PART(LAYER_TRANSPARENT, 0, 0, 0, NULL),
         GEO_ANIMATED_PART(LAYER_TRANSPARENT, 0, 0, 0, NULL),
         GEO_ANIMATED_PART(LAYER_TRANSPARENT, 0, 0, 0, NULL),
         GEO_ANIMATED_PART(LAYER_TRANSPARENT, 0, 0, 0, NULL),
         GEO_ANIMATED_PART(LAYER_TRANSPARENT, 0, 0, 0, NULL),
         GEO_ANIMATED_PART(LAYER_TRANSPARENT, 0, 0, 0, NULL),
         GEO_ANIMATED_PART(LAYER_TRANSPARENT, 0, 0, 0, NULL),
         GEO_ANIMATED_PART(LAYER_TRANSPARENT, 0, 0, 0, NULL),
      GEO_CLOSE_NODE(),
   GEO_CLOSE_NODE(),
   GEO_RETURN(),
};

// 0x0D000770
const GeoLayout bowser_geo_000770[] = {
   GEO_NODE_START(),
   GEO_OPEN_NODE(),
#ifdef VERSION_JP
      GEO_ANIMATED_PART(LAYER_TRANSPARENT, 0, 0, 0, bowser_root_mesh),
#else
      GEO_ANIMATED_PART(LAYER_TRANSPARENT, 0, 0, 0, bowser_root_mesh),
#endif
      GEO_OPEN_NODE(),
         GEO_ANIMATED_PART(LAYER_TRANSPARENT, -89, -2, -18, NULL),
         GEO_OPEN_NODE(),
            GEO_ANIMATED_PART(LAYER_TRANSPARENT, 0, 0, 0, NULL),
            GEO_OPEN_NODE(),
               GEO_ANIMATED_PART(LAYER_TRANSPARENT, 69, 0, 0, NULL),
               GEO_OPEN_NODE(),
                  GEO_ANIMATED_PART(LAYER_TRANSPARENT, 85, 0, 0, NULL),
                  GEO_OPEN_NODE(),
                     GEO_ANIMATED_PART(LAYER_TRANSPARENT, 0, 0, 0, bowser_000_offset_004_mesh),
                  GEO_CLOSE_NODE(),
                  GEO_ANIMATED_PART(LAYER_TRANSPARENT, 0, 0, 0, bowser_002_offset_mesh),
               GEO_CLOSE_NODE(),
            GEO_CLOSE_NODE(),
         GEO_CLOSE_NODE(),
         GEO_ANIMATED_PART(LAYER_TRANSPARENT, 0, -32, -112, NULL),
         GEO_OPEN_NODE(),
            GEO_ANIMATED_PART(LAYER_TRANSPARENT, 0, 0, 0, NULL),
            GEO_OPEN_NODE(),
               GEO_ANIMATED_PART(LAYER_TRANSPARENT, 0, 0, 0, bowser_000_offset_006_mesh),
               GEO_ASM(0, geo_update_body_rot_from_parent),
            GEO_CLOSE_NODE(),
         GEO_CLOSE_NODE(),
         GEO_ANIMATED_PART(LAYER_TRANSPARENT, 118, 67, 105, NULL),
         GEO_OPEN_NODE(),
            GEO_ANIMATED_PART(LAYER_TRANSPARENT, 0, 0, 0, NULL),
            GEO_OPEN_NODE(),
               GEO_ANIMATED_PART(LAYER_TRANSPARENT, 65, 0, 0, NULL),
               GEO_OPEN_NODE(),
                  GEO_ANIMATED_PART(LAYER_TRANSPARENT, 49, 0, 0, NULL),
                  GEO_OPEN_NODE(),
                     GEO_ANIMATED_PART(LAYER_TRANSPARENT, 0, 0, 0, bowser_000_offset_010_mesh),
                  GEO_CLOSE_NODE(),
                  GEO_ANIMATED_PART(LAYER_TRANSPARENT, 0, 0, 0, bowser_002_offset_002_mesh),
               GEO_CLOSE_NODE(),
               GEO_ANIMATED_PART(LAYER_TRANSPARENT, 0, 0, 0, bowser_002_offset_003_mesh),
            GEO_CLOSE_NODE(),
         GEO_CLOSE_NODE(),
         GEO_ANIMATED_PART(LAYER_TRANSPARENT, 0, 136, 130, NULL),
         GEO_OPEN_NODE(),
            GEO_ANIMATED_PART(LAYER_TRANSPARENT, 0, 0, 0, NULL),
            GEO_OPEN_NODE(),
               GEO_ANIMATED_PART(LAYER_TRANSPARENT, 61, 0, 0, NULL),
               GEO_OPEN_NODE(),
                  GEO_ANIMATED_PART(LAYER_TRANSPARENT, -13, 258, 0, bowser_000_offset_013_mesh),
               GEO_CLOSE_NODE(),
               GEO_SWITCH_CASE(9, geo_switch_bowser_eyes),
               GEO_OPEN_NODE(),
                  GEO_ANIMATED_PART(LAYER_TRANSPARENT, 0, 0, 0, bowser_000_offset_014_mesh),
				  /*
                  GEO_ANIMATED_PART(LAYER_TRANSPARENT, 0, 0, 0, bowser_seg6_dl_060423A0),
                  GEO_ANIMATED_PART(LAYER_TRANSPARENT, 0, 0, 0, bowser_seg6_dl_060423F8),
                  GEO_ANIMATED_PART(LAYER_TRANSPARENT, 0, 0, 0, bowser_seg6_dl_06042450),
                  GEO_ANIMATED_PART(LAYER_TRANSPARENT, 0, 0, 0, bowser_seg6_dl_060424A8),
                  GEO_ANIMATED_PART(LAYER_TRANSPARENT, 0, 0, 0, bowser_seg6_dl_06042500),
                  GEO_ANIMATED_PART(LAYER_TRANSPARENT, 0, 0, 0, bowser_seg6_dl_06042558),
                  GEO_ANIMATED_PART(LAYER_TRANSPARENT, 0, 0, 0, bowser_seg6_dl_060425B0),
                  GEO_ANIMATED_PART(LAYER_TRANSPARENT, 0, 0, 0, bowser_seg6_dl_06042608),
				  */
               GEO_CLOSE_NODE(),
            GEO_CLOSE_NODE(),
         GEO_CLOSE_NODE(),
         GEO_ANIMATED_PART(LAYER_TRANSPARENT, -118, 67, 105, NULL),
         GEO_OPEN_NODE(),
            GEO_ANIMATED_PART(LAYER_TRANSPARENT, 0, 0, 0, NULL),
            GEO_OPEN_NODE(),
               GEO_ANIMATED_PART(LAYER_TRANSPARENT, 65, 0, 0, NULL),
               GEO_OPEN_NODE(),
                  GEO_ANIMATED_PART(LAYER_TRANSPARENT, 49, 0, 0, NULL),
                  GEO_OPEN_NODE(),
                     GEO_ANIMATED_PART(LAYER_TRANSPARENT, 0, 0, 0, bowser_000_offset_018_mesh),
                  GEO_CLOSE_NODE(),
                  GEO_ANIMATED_PART(LAYER_TRANSPARENT, 0, 0, 0, bowser_002_offset_004_mesh),
               GEO_CLOSE_NODE(),
               GEO_ANIMATED_PART(LAYER_TRANSPARENT, 0, 0, 0, bowser_002_offset_005_mesh),
            GEO_CLOSE_NODE(),
         GEO_CLOSE_NODE(),
         GEO_ANIMATED_PART(LAYER_TRANSPARENT, 89, -2, -18, NULL),
         GEO_OPEN_NODE(),
            GEO_ANIMATED_PART(LAYER_TRANSPARENT, 0, 0, 0, NULL),
            GEO_OPEN_NODE(),
               GEO_ANIMATED_PART(LAYER_TRANSPARENT, 69, 0, 0, NULL),
               GEO_OPEN_NODE(),
                  GEO_ANIMATED_PART(LAYER_TRANSPARENT, 85, 0, 0, NULL),
                  GEO_OPEN_NODE(),
                     GEO_ANIMATED_PART(LAYER_TRANSPARENT, 0, 0, 0, bowser_000_offset_022_mesh),
                  GEO_CLOSE_NODE(),
#ifdef VERSION_JP
                  GEO_ANIMATED_PART(LAYER_TRANSPARENT, 0, 0, 0, bowser_002_offset_006_mesh),
#else
                  GEO_ANIMATED_PART(LAYER_TRANSPARENT, 0, 0, 0, bowser_002_offset_006_mesh),
#endif
               GEO_CLOSE_NODE(),
            GEO_CLOSE_NODE(),
         GEO_CLOSE_NODE(),
         GEO_ANIMATED_PART(LAYER_TRANSPARENT, 0, 0, 0, NULL),
         GEO_ANIMATED_PART(LAYER_TRANSPARENT, 0, 0, 0, NULL),
         GEO_ANIMATED_PART(LAYER_TRANSPARENT, 0, 0, 0, NULL),
         GEO_ANIMATED_PART(LAYER_TRANSPARENT, 0, 0, 0, NULL),
         GEO_ANIMATED_PART(LAYER_TRANSPARENT, 0, 0, 0, NULL),
         GEO_ANIMATED_PART(LAYER_TRANSPARENT, 0, 0, 0, NULL),
         GEO_ANIMATED_PART(LAYER_TRANSPARENT, 0, 0, 0, NULL),
         GEO_ANIMATED_PART(LAYER_TRANSPARENT, 0, 0, 0, NULL),
         GEO_ANIMATED_PART(LAYER_TRANSPARENT, 0, 0, 0, NULL),
      GEO_CLOSE_NODE(),
   GEO_CLOSE_NODE(),
   GEO_RETURN(),
};

#ifndef VERSION_JP
// 0x0D000AB8
const GeoLayout bowser_shadow_geo[] = {
   GEO_SHADOW(0x00, 0x9B, 400),
   GEO_RETURN(),
};
#endif

// 0x0D000AB8 / 0AC4
const GeoLayout bowser_geo[] = {
   GEO_NODE_START(),
   GEO_OPEN_NODE(),
      GEO_ASM(0, geo_update_layer_transparency),
#ifdef VERSION_JP
      GEO_SWITCH_CASE(2, geo_switch_anim_state),
#endif
#ifndef VERSION_JP
      GEO_SWITCH_CASE(3, geo_switch_anim_state),
#endif
      GEO_OPEN_NODE(),
         GEO_NODE_START(),
         GEO_OPEN_NODE(),
            GEO_ASM(0, geo_bits_bowser_coloring),
            GEO_BRANCH(1, bowser_geo_0000D8),
         GEO_CLOSE_NODE(),

         GEO_NODE_START(),
         GEO_OPEN_NODE(),
            GEO_ASM(0, geo_bits_bowser_coloring),
            GEO_BRANCH(1, bowser_geo_000424),
         GEO_CLOSE_NODE(),

#ifndef VERSION_JP
         GEO_NODE_START(),
         GEO_OPEN_NODE(),
            GEO_ASM(0, geo_bits_bowser_coloring),
            GEO_BRANCH(1, bowser_shadow_geo),
         GEO_CLOSE_NODE(),
#endif
      GEO_CLOSE_NODE(),

   GEO_CLOSE_NODE(),
   GEO_END(),
};

// 0x0D000B18 / 0B40
const GeoLayout bowser2_geo[] = {
   GEO_NODE_START(),
   GEO_OPEN_NODE(),
      GEO_ASM(0, geo_update_layer_transparency),

#ifdef VERSION_JP
      GEO_SWITCH_CASE(2, geo_switch_anim_state),
#endif
#ifndef VERSION_JP
      GEO_SWITCH_CASE(3, geo_switch_anim_state),
#endif
      GEO_OPEN_NODE(),

         GEO_NODE_START(),
         GEO_OPEN_NODE(),
            GEO_ASM(0, geo_bits_bowser_coloring),
            GEO_BRANCH(1, bowser_geo_0000D8),
         GEO_CLOSE_NODE(),

         GEO_NODE_START(),
         GEO_OPEN_NODE(),
            GEO_ASM(0, geo_bits_bowser_coloring),
            GEO_BRANCH(1, bowser_geo_000770),
         GEO_CLOSE_NODE(),

#ifndef VERSION_JP
         GEO_NODE_START(),
         GEO_OPEN_NODE(),
            GEO_ASM(0, geo_bits_bowser_coloring),
            GEO_BRANCH(1, bowser_shadow_geo),
         GEO_CLOSE_NODE(),
#endif
      GEO_CLOSE_NODE(),

   GEO_CLOSE_NODE(),
   GEO_END(),
};
