#include "src/game/envfx_snow.h"

const GeoLayout snufit_geo[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_SHADOW(0, 150, 100),
		GEO_OPEN_NODE(),
			GEO_SCALE(0, 16384),
			GEO_OPEN_NODE(),
				GEO_ASM(0, geo_snufit_move_mask),
				GEO_TRANSLATE_NODE(0, 0, 0, 0),
				GEO_OPEN_NODE(),
					GEO_DISPLAY_LIST(1, NULL),
				GEO_CLOSE_NODE(),
				GEO_DISPLAY_LIST(1, snufit_003_displaylist_mesh),
				GEO_DISPLAY_LIST(1, snufit_004_displaylist_mesh),
				GEO_DISPLAY_LIST(1, NULL),
				GEO_BILLBOARD_WITH_PARAMS(0, 0, 0, 0),
				GEO_OPEN_NODE(),
					GEO_ASM(0, geo_snufit_scale_body),
					GEO_SCALE(0, 1),
					GEO_OPEN_NODE(),
						GEO_DISPLAY_LIST(4, NULL),
					GEO_CLOSE_NODE(),
				GEO_CLOSE_NODE(),
			GEO_CLOSE_NODE(),
		GEO_CLOSE_NODE(),
		GEO_DISPLAY_LIST(0, snufit_material_revert_render_settings),
		GEO_DISPLAY_LIST(1, snufit_material_revert_render_settings),
		GEO_DISPLAY_LIST(2, snufit_material_revert_render_settings),
		GEO_DISPLAY_LIST(3, snufit_material_revert_render_settings),
		GEO_DISPLAY_LIST(4, snufit_material_revert_render_settings),
		GEO_DISPLAY_LIST(5, snufit_material_revert_render_settings),
		GEO_DISPLAY_LIST(6, snufit_material_revert_render_settings),
		GEO_DISPLAY_LIST(7, snufit_material_revert_render_settings),
	GEO_CLOSE_NODE(),
	GEO_END(),
};
