#include "src/game/envfx_snow.h"

const GeoLayout chilly_chief_geo[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_SHADOW(0, 200, 70),
		GEO_OPEN_NODE(),
			GEO_SCALE(0, 24576),
			GEO_OPEN_NODE(),
				GEO_ANIMATED_PART(1, 0, 0, 0, NULL),
				GEO_OPEN_NODE(),
					GEO_ANIMATED_PART(1, 0, 0, 0, NULL),
					GEO_OPEN_NODE(),
						GEO_ANIMATED_PART(1, 0, 0, 75, NULL),
						GEO_OPEN_NODE(),
							GEO_ANIMATED_PART(1, 0, 0, 0, NULL),
							GEO_OPEN_NODE(),
								GEO_ANIMATED_PART(1, 146, 0, 0, NULL),
								GEO_OPEN_NODE(),
									GEO_ANIMATED_PART(1, 0, 0, 0, chillychief_000_offset_004_mesh),
								GEO_CLOSE_NODE(),
							GEO_CLOSE_NODE(),
						GEO_CLOSE_NODE(),
						GEO_ANIMATED_PART(1, 0, 0, -75, NULL),
						GEO_OPEN_NODE(),
							GEO_ANIMATED_PART(1, 0, 0, 0, NULL),
							GEO_OPEN_NODE(),
								GEO_ANIMATED_PART(1, 146, 0, 0, NULL),
								GEO_OPEN_NODE(),
									GEO_ANIMATED_PART(1, 0, 0, 0, chillychief_000_offset_007_mesh),
								GEO_CLOSE_NODE(),
							GEO_CLOSE_NODE(),
						GEO_CLOSE_NODE(),
						GEO_ANIMATED_PART(1, 0, 0, 0, NULL),
						GEO_OPEN_NODE(),
							GEO_SCALE(0, 160576),
							//GEO_BILLBOARD_WITH_PARAMS(0, 0, 0, 0),
							GEO_OPEN_NODE(),
								GEO_DISPLAY_LIST(4, chillychief_000_displaylist_mesh),
							GEO_CLOSE_NODE(),
						GEO_CLOSE_NODE(),
						GEO_ANIMATED_PART(1, 0, 0, 0, NULL),
						GEO_ANIMATED_PART(4, 0, 0, 0, NULL),
					GEO_CLOSE_NODE(),
				GEO_CLOSE_NODE(),
			GEO_CLOSE_NODE(),
		GEO_CLOSE_NODE(),
		GEO_DISPLAY_LIST(0, chillychief_material_revert_render_settings),
		GEO_DISPLAY_LIST(1, chillychief_material_revert_render_settings),
		GEO_DISPLAY_LIST(2, chillychief_material_revert_render_settings),
		GEO_DISPLAY_LIST(3, chillychief_material_revert_render_settings),
		GEO_DISPLAY_LIST(4, chillychief_material_revert_render_settings),
		GEO_DISPLAY_LIST(5, chillychief_material_revert_render_settings),
		GEO_DISPLAY_LIST(6, chillychief_material_revert_render_settings),
		GEO_DISPLAY_LIST(7, chillychief_material_revert_render_settings),
	GEO_CLOSE_NODE(),
	GEO_END(),
};

const GeoLayout chilly_chief_big_geo[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_SHADOW(0, 200, 70),
		GEO_OPEN_NODE(),
		GEO_SCALE(0x00, 49152),
			GEO_OPEN_NODE(),
				GEO_ANIMATED_PART(1, 0, 0, 0, NULL),
				GEO_OPEN_NODE(),
					GEO_ANIMATED_PART(1, 0, 0, 0, NULL),
					GEO_OPEN_NODE(),
						GEO_ANIMATED_PART(1, 0, 0, 75, NULL),
						GEO_OPEN_NODE(),
							GEO_ANIMATED_PART(1, 0, 0, 0, NULL),
							GEO_OPEN_NODE(),
								GEO_ANIMATED_PART(1, 146, 0, 0, NULL),
								GEO_OPEN_NODE(),
									GEO_ANIMATED_PART(1, 0, 0, 0, chillychief_000_offset_004_mesh),
								GEO_CLOSE_NODE(),
							GEO_CLOSE_NODE(),
						GEO_CLOSE_NODE(),
						GEO_ANIMATED_PART(1, 0, 0, -75, NULL),
						GEO_OPEN_NODE(),
							GEO_ANIMATED_PART(1, 0, 0, 0, NULL),
							GEO_OPEN_NODE(),
								GEO_ANIMATED_PART(1, 146, 0, 0, NULL),
								GEO_OPEN_NODE(),
									GEO_ANIMATED_PART(1, 0, 0, 0, chillychief_000_offset_007_mesh),
								GEO_CLOSE_NODE(),
							GEO_CLOSE_NODE(),
						GEO_CLOSE_NODE(),
						GEO_ANIMATED_PART(1, 0, 0, 0, NULL),
						GEO_OPEN_NODE(),
							GEO_SCALE(0, 160576),
							//GEO_BILLBOARD_WITH_PARAMS(0, 0, 0, 0),
							GEO_OPEN_NODE(),
								GEO_DISPLAY_LIST(4, chillychief_000_displaylist_mesh),
							GEO_CLOSE_NODE(),
						GEO_CLOSE_NODE(),
						GEO_ANIMATED_PART(1, 0, 0, 0, NULL),
						GEO_ANIMATED_PART(4, 0, 0, 0, NULL),
					GEO_CLOSE_NODE(),
				GEO_CLOSE_NODE(),
			GEO_CLOSE_NODE(),
		GEO_CLOSE_NODE(),
		GEO_DISPLAY_LIST(0, chillychief_material_revert_render_settings),
		GEO_DISPLAY_LIST(1, chillychief_material_revert_render_settings),
		GEO_DISPLAY_LIST(2, chillychief_material_revert_render_settings),
		GEO_DISPLAY_LIST(3, chillychief_material_revert_render_settings),
		GEO_DISPLAY_LIST(4, chillychief_material_revert_render_settings),
		GEO_DISPLAY_LIST(5, chillychief_material_revert_render_settings),
		GEO_DISPLAY_LIST(6, chillychief_material_revert_render_settings),
		GEO_DISPLAY_LIST(7, chillychief_material_revert_render_settings),
	GEO_CLOSE_NODE(),
	GEO_END(),
};
