// 0x0C00010C
const GeoLayout unagi_geo[] = {
   GEO_CULLING_RADIUS(2000),
   GEO_OPEN_NODE(),
      GEO_SCALE(0x00, 16384),
      GEO_OPEN_NODE(),
         GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, NULL),
         GEO_OPEN_NODE(),
            GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, unagi_000_offset_mesh),
            GEO_OPEN_NODE(),
			GEO_DISPLAY_LIST(LAYER_OPAQUE, unagi_000_offset_001_skinned),
			GEO_ANIMATED_PART(LAYER_OPAQUE, 245, 0, 0, unagi_000_offset_001_mesh),
               GEO_OPEN_NODE(),
				GEO_DISPLAY_LIST(LAYER_OPAQUE, unagi_000_offset_002_skinned),
				GEO_ANIMATED_PART(LAYER_OPAQUE, 494, 0, 0, unagi_000_offset_002_mesh),
                  GEO_OPEN_NODE(),
					GEO_DISPLAY_LIST(LAYER_OPAQUE, unagi_000_offset_003_skinned),
					GEO_ANIMATED_PART(LAYER_OPAQUE, 475, 0, 0, unagi_000_offset_003_mesh),
                     GEO_OPEN_NODE(),
                        GEO_SWITCH_CASE(2, geo_switch_anim_state),
                        GEO_OPEN_NODE(),
                           GEO_NODE_START(),
                           GEO_NODE_START(),
                           GEO_OPEN_NODE(),
                              GEO_SCALE(0x00, 16384),
                              GEO_OPEN_NODE(),
                                 GEO_TRANSLATE_ROTATE_WITH_DL(LAYER_OPAQUE, 2000, 0, 0, 0, 0, 0, star_complete),
                                 GEO_TRANSLATE_ROTATE_WITH_DL(LAYER_ALPHA, 2000, 0, 0, 0, 0, 0, star_complete),
                              GEO_CLOSE_NODE(),
                           GEO_CLOSE_NODE(),
                        GEO_CLOSE_NODE(),
                     GEO_CLOSE_NODE(),
                  GEO_CLOSE_NODE(),
               GEO_CLOSE_NODE(),
			GEO_DISPLAY_LIST(1, unagi_000_offset_004_skinned),
			GEO_ANIMATED_PART(1, -254, 0, 0, NULL),
               GEO_OPEN_NODE(),
                  GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, unagi_000_offset_004_mesh),
                  GEO_OPEN_NODE(),
                     GEO_ANIMATED_PART(LAYER_ALPHA, 527, 0, 0, NULL),
                     GEO_OPEN_NODE(),
                        GEO_ANIMATED_PART(LAYER_OPAQUE, 226, 65, 0, NULL),
                        GEO_OPEN_NODE(),
                           GEO_ANIMATED_PART(LAYER_ALPHA, 0, 0, 0, NULL),
                           GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, NULL),
                           GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, NULL),
                        GEO_CLOSE_NODE(),
                     GEO_CLOSE_NODE(),
                     GEO_ANIMATED_PART(LAYER_ALPHA, 527, 0, 0, NULL),
					 GEO_DISPLAY_LIST(LAYER_OPAQUE, unagi_003_offset_skinned),
                     GEO_ANIMATED_PART(LAYER_OPAQUE, 527, 0, 0, unagi_003_offset_mesh),
                     GEO_ANIMATED_PART(LAYER_OPAQUE, 527, 0, 0, NULL),
                  GEO_CLOSE_NODE(),
               GEO_CLOSE_NODE(),
            GEO_CLOSE_NODE(),
         GEO_CLOSE_NODE(),
      GEO_CLOSE_NODE(),
   GEO_CLOSE_NODE(),
   GEO_END(),
};
