extern const GeoLayout bubba_bigmouth[];
extern const GeoLayout bubba_geo[];
extern Vtx bubba_000_displaylist_mesh_vtx_0[407];
extern Gfx bubba_000_displaylist_mesh_tri_0[];
extern Vtx bubba_000_displaylist_mesh_vtx_1[486];
extern Gfx bubba_000_displaylist_mesh_tri_1[];
extern Vtx bubba_000_displaylist_mesh_vtx_2[1569];
extern Gfx bubba_000_displaylist_mesh_tri_2[];
extern Vtx bubba_000_displaylist_mesh_vtx_3[302];
extern Gfx bubba_000_displaylist_mesh_tri_3[];
extern Vtx bubba_000_displaylist_mesh_vtx_4[123];
extern Gfx bubba_000_displaylist_mesh_tri_4[];
extern Vtx bubba_000_displaylist_mesh_vtx_5[7];
extern Gfx bubba_000_displaylist_mesh_tri_5[];
extern Vtx bubba_000_displaylist_mesh_vtx_6[149];
extern Gfx bubba_000_displaylist_mesh_tri_6[];
extern Vtx bubba_000_switch_bigmouth_mesh_vtx_0[407];
extern Gfx bubba_000_switch_bigmouth_mesh_tri_0[];
extern Vtx bubba_000_switch_bigmouth_mesh_vtx_1[486];
extern Gfx bubba_000_switch_bigmouth_mesh_tri_1[];
extern Vtx bubba_000_switch_bigmouth_mesh_vtx_2[1569];
extern Gfx bubba_000_switch_bigmouth_mesh_tri_2[];
extern Vtx bubba_000_switch_bigmouth_mesh_vtx_3[300];
extern Gfx bubba_000_switch_bigmouth_mesh_tri_3[];
extern Vtx bubba_000_switch_bigmouth_mesh_vtx_4[123];
extern Gfx bubba_000_switch_bigmouth_mesh_tri_4[];
extern Vtx bubba_000_switch_bigmouth_mesh_vtx_5[16];
extern Gfx bubba_000_switch_bigmouth_mesh_tri_5[];
extern Vtx bubba_000_switch_bigmouth_mesh_vtx_6[149];
extern Gfx bubba_000_switch_bigmouth_mesh_tri_6[];

extern Gfx bubba_000_displaylist_mesh[];
extern Gfx bubba_000_switch_bigmouth_mesh[];
extern Gfx bubba_material_revert_render_settings[];

