#include "src/game/envfx_snow.h"

const GeoLayout chain_chomp_geo[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_SHADOW(0, 150, 200),
		GEO_OPEN_NODE(),
			GEO_SCALE(0, 16384),
			GEO_OPEN_NODE(),
				GEO_ANIMATED_PART(1, 0, 0, 0, NULL),
				GEO_OPEN_NODE(),
					GEO_ANIMATED_PART(1, 0, 0, 0, chain_chomp_000_offset_mesh),
					GEO_ANIMATED_PART(1, 0, 0, 0, chain_chomp_001_offset_mesh),
				GEO_CLOSE_NODE(),
				GEO_ANIMATED_PART(1, 0, 0, 0, NULL),
				GEO_OPEN_NODE(),
					GEO_ANIMATED_PART(1, 0, 0, 0, chain_chomp_000_offset_001_mesh),
					GEO_ANIMATED_PART(1, 0, 0, 0, chain_chomp_001_offset_001_mesh),
					GEO_ANIMATED_PART(4, 0, 0, 0, chain_chomp_002_offset_001_mesh),
				GEO_CLOSE_NODE(),
			GEO_CLOSE_NODE(),
		GEO_CLOSE_NODE(),
		GEO_DISPLAY_LIST(0, chain_chomp_material_revert_render_settings),
		GEO_DISPLAY_LIST(1, chain_chomp_material_revert_render_settings),
		GEO_DISPLAY_LIST(2, chain_chomp_material_revert_render_settings),
		GEO_DISPLAY_LIST(3, chain_chomp_material_revert_render_settings),
		GEO_DISPLAY_LIST(4, chain_chomp_material_revert_render_settings),
		GEO_DISPLAY_LIST(5, chain_chomp_material_revert_render_settings),
		GEO_DISPLAY_LIST(6, chain_chomp_material_revert_render_settings),
		GEO_DISPLAY_LIST(7, chain_chomp_material_revert_render_settings),
	GEO_CLOSE_NODE(),
	GEO_END(),
};
