#include "src/game/envfx_snow.h"

const GeoLayout monty_mole_geo[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_NODE_START(),
		GEO_OPEN_NODE(),
			GEO_SCALE(0, 16384),
			GEO_OPEN_NODE(),
				GEO_ANIMATED_PART(1, 0, 0, 0, NULL),
				GEO_OPEN_NODE(),
					GEO_ANIMATED_PART(1, 0, 0, 0, monty_mole_000_offset_mesh),
					GEO_OPEN_NODE(),
						GEO_ANIMATED_PART(1, 116, 0, 0, NULL),
						GEO_ANIMATED_PART(4, 116, 0, 0, NULL),
						GEO_ANIMATED_PART(1, -68, -5, -40, NULL),
						GEO_OPEN_NODE(),
							GEO_ANIMATED_PART(1, 0, 0, 0, monty_mole_000_offset_002_mesh),
						GEO_CLOSE_NODE(),
						GEO_ANIMATED_PART(1, -68, -5, 40, NULL),
						GEO_OPEN_NODE(),
							GEO_ANIMATED_PART(1, 0, 0, 0, monty_mole_000_offset_003_mesh),
						GEO_CLOSE_NODE(),
						GEO_ANIMATED_PART(1, 43, 1, 87, NULL),
						GEO_OPEN_NODE(),
							GEO_ANIMATED_PART(1, 0, 0, 0, NULL),
							GEO_OPEN_NODE(),
								GEO_ANIMATED_PART(1, 80, 0, 0, monty_mole_000_offset_005_mesh),
							GEO_CLOSE_NODE(),
						GEO_CLOSE_NODE(),
						GEO_ANIMATED_PART(1, 43, 1, -88, NULL),
						GEO_OPEN_NODE(),
							GEO_ANIMATED_PART(1, 0, 0, 0, monty_mole_000_offset_006_mesh),
							GEO_OPEN_NODE(),
								GEO_ANIMATED_PART(1, 80, 0, 0, NULL),
								GEO_ASM(0, geo_update_projectile_pos_from_parent),
							GEO_CLOSE_NODE(),
						GEO_CLOSE_NODE(),
					GEO_CLOSE_NODE(),
				GEO_CLOSE_NODE(),
			GEO_CLOSE_NODE(),
		GEO_CLOSE_NODE(),
		GEO_DISPLAY_LIST(0, monty_mole_material_revert_render_settings),
		GEO_DISPLAY_LIST(1, monty_mole_material_revert_render_settings),
		GEO_DISPLAY_LIST(2, monty_mole_material_revert_render_settings),
		GEO_DISPLAY_LIST(3, monty_mole_material_revert_render_settings),
		GEO_DISPLAY_LIST(4, monty_mole_material_revert_render_settings),
		GEO_DISPLAY_LIST(5, monty_mole_material_revert_render_settings),
		GEO_DISPLAY_LIST(6, monty_mole_material_revert_render_settings),
		GEO_DISPLAY_LIST(7, monty_mole_material_revert_render_settings),
	GEO_CLOSE_NODE(),
	GEO_END(),
};
