#include "src/game/envfx_snow.h"

const GeoLayout goomba_000_switch_opt1[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_ANIMATED_PART(1, 48, 0, 0, goomba_000_offset_001_mesh_mat_override_blink_0),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout goomba_geo[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_SHADOW(0, 150, 100),
		GEO_OPEN_NODE(),
			GEO_SCALE(0, 16384),
			GEO_OPEN_NODE(),
				GEO_ANIMATED_PART(1, 0, 0, 0, NULL),
				GEO_OPEN_NODE(),
					GEO_ANIMATED_PART(1, 0, 0, 0, NULL),
					GEO_OPEN_NODE(),
						GEO_BILLBOARD_WITH_PARAMS(0, 0, 0, 0),
						GEO_OPEN_NODE(),
							GEO_DISPLAY_LIST(4, NULL),
						GEO_CLOSE_NODE(),
						GEO_SWITCH_CASE(2, geo_switch_anim_state),
						GEO_OPEN_NODE(),
							GEO_NODE_START(),
							GEO_OPEN_NODE(),
								GEO_ANIMATED_PART(1, 48, 0, 0, goomba_000_offset_001_mesh),
							GEO_CLOSE_NODE(),
							GEO_BRANCH(1, goomba_000_switch_opt1),
						GEO_CLOSE_NODE(),
						GEO_ANIMATED_PART(1, -60, -16, 45, NULL),
						GEO_OPEN_NODE(),
							GEO_ANIMATED_PART(1, 0, 0, 0, goomba_000_offset_002_mesh),
						GEO_CLOSE_NODE(),
						GEO_ANIMATED_PART(1, -60, -16, -45, NULL),
						GEO_OPEN_NODE(),
							GEO_ANIMATED_PART(1, 0, 0, 0, goomba_000_offset_003_mesh),
						GEO_CLOSE_NODE(),
					GEO_CLOSE_NODE(),
				GEO_CLOSE_NODE(),
			GEO_CLOSE_NODE(),
		GEO_CLOSE_NODE(),
		GEO_DISPLAY_LIST(0, goomba_material_revert_render_settings),
		GEO_DISPLAY_LIST(1, goomba_material_revert_render_settings),
		GEO_DISPLAY_LIST(2, goomba_material_revert_render_settings),
		GEO_DISPLAY_LIST(3, goomba_material_revert_render_settings),
		GEO_DISPLAY_LIST(4, goomba_material_revert_render_settings),
		GEO_DISPLAY_LIST(5, goomba_material_revert_render_settings),
		GEO_DISPLAY_LIST(6, goomba_material_revert_render_settings),
		GEO_DISPLAY_LIST(7, goomba_material_revert_render_settings),
	GEO_CLOSE_NODE(),
	GEO_END(),
};
