#include "src/game/envfx_snow.h"

const GeoLayout mr_blizzard_hidden_geo[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_SCALE(0, 16384),
		GEO_OPEN_NODE(),
			GEO_ANIMATED_PART(1, 0, 0, 0, NULL),
			GEO_OPEN_NODE(),
				GEO_ANIMATED_PART(1, 0, 0, 0, NULL),
				GEO_OPEN_NODE(),
					GEO_SCALE(0x00, 275000),
					//GEO_BILLBOARD_WITH_PARAMS(0, 0, 0, 0),
					GEO_OPEN_NODE(),
						GEO_DISPLAY_LIST(4, snowman_000_displaylist_mesh),
					GEO_CLOSE_NODE(),
					GEO_ANIMATED_PART(1, 356, 0, 0, NULL),
					GEO_OPEN_NODE(),
					GEO_SCALE(0x00, 275000),
					//GEO_BILLBOARD_WITH_PARAMS(0, 0, 0, 0),
						GEO_OPEN_NODE(),
							GEO_DISPLAY_LIST(4, snowman_000_displaylist_001_mesh),
						GEO_CLOSE_NODE(),
					GEO_CLOSE_NODE(),
					GEO_ANIMATED_PART(4, 356, 0, 0, NULL),
					GEO_ANIMATED_PART(4, 356, 0, 0, NULL),
					GEO_SWITCH_CASE(2, geo_switch_anim_state),
					GEO_OPEN_NODE(),
						GEO_NODE_START(),
						GEO_OPEN_NODE(),
							GEO_NODE_START(),
						GEO_CLOSE_NODE(),
					GEO_CLOSE_NODE(),
					GEO_ANIMATED_PART(1, 89, 0, -229, NULL),
					GEO_OPEN_NODE(),
						GEO_ANIMATED_PART(1, 0, 0, 0, snowman_000_offset_002_mesh),
						GEO_OPEN_NODE(),
							GEO_ANIMATED_PART(1, 68, 0, 0, snowman_000_offset_003_mesh),
							GEO_ASM(0, geo_update_projectile_pos_from_parent),
						GEO_CLOSE_NODE(),
					GEO_CLOSE_NODE(),
					GEO_ANIMATED_PART(1, 356, 0, 0, NULL),
				GEO_CLOSE_NODE(),
			GEO_CLOSE_NODE(),
		GEO_CLOSE_NODE(),
		GEO_DISPLAY_LIST(0, snowman_material_revert_render_settings),
		GEO_DISPLAY_LIST(1, snowman_material_revert_render_settings),
		GEO_DISPLAY_LIST(2, snowman_material_revert_render_settings),
		GEO_DISPLAY_LIST(3, snowman_material_revert_render_settings),
		GEO_DISPLAY_LIST(4, snowman_material_revert_render_settings),
		GEO_DISPLAY_LIST(5, snowman_material_revert_render_settings),
		GEO_DISPLAY_LIST(6, snowman_material_revert_render_settings),
		GEO_DISPLAY_LIST(7, snowman_material_revert_render_settings),
	GEO_CLOSE_NODE(),
	GEO_END(),
};

// 0x0C000348
const GeoLayout mr_blizzard_geo[] = {
   GEO_SHADOW(SHADOW_CIRCLE_4_VERTS, 0xB4, 160),
   GEO_OPEN_NODE(),
      GEO_BRANCH_AND_LINK(mr_blizzard_hidden_geo),
   GEO_CLOSE_NODE(),
   GEO_END(),
};

