#include "src/game/envfx_snow.h"

const GeoLayout peach_halfclosedeye[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(1, peach_000_switch_peach_halfclosedeye_mesh),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout peach_quarterclosedeye[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(1, peach_000_switch_peach_quaterclosedeye_mesh),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout peach_closedeye[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(1, peach_000_switch_peach_closedeye_mesh),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout peach_001_switch_opt1_jump_peach_halfclosedeye[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(5, peach_000_switch_peach_halfclosedeye_mesh),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout peach_001_switch_opt1_jump_peach_quarterclosedeye[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(5, peach_000_switch_peach_quaterclosedeye_mesh),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout peach_001_switch_opt1_jump_peach_closedeye[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(5, peach_000_switch_peach_closedeye_mesh),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout peach_001_switch_opt1_000_switch_opt4[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(5, peach_000_displaylist_mesh_mat_override_skin_0),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout peach_001_switch_opt1[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_NODE_START(),
		GEO_OPEN_NODE(),
			GEO_ANIMATED_PART(1, 0, 0, 0, NULL),
			GEO_OPEN_NODE(),
				GEO_ANIMATED_PART(5, 0, 0, 0, peach_000_offset_mesh),
				GEO_OPEN_NODE(),
					GEO_ANIMATED_PART(5, 78, 0, 0, peach_000_offset_001_mesh),
					GEO_OPEN_NODE(),
						GEO_ANIMATED_PART(1, 132, 0, 0, NULL),
						GEO_OPEN_NODE(),
							GEO_SWITCH_CASE(8, geo_switch_peach_eyes),
							GEO_OPEN_NODE(),
								GEO_NODE_START(),
								GEO_OPEN_NODE(),
									GEO_DISPLAY_LIST(5, peach_000_displaylist_mesh),
								GEO_CLOSE_NODE(),
								GEO_BRANCH(1, peach_001_switch_opt1_jump_peach_halfclosedeye),
								GEO_BRANCH(1, peach_001_switch_opt1_jump_peach_quarterclosedeye),
								GEO_BRANCH(1, peach_001_switch_opt1_jump_peach_closedeye),
								GEO_BRANCH(1, peach_001_switch_opt1_000_switch_opt4),
							GEO_CLOSE_NODE(),
							GEO_ANIMATED_PART(1, 38, -78, 0, NULL),
							GEO_OPEN_NODE(),
								GEO_ANIMATED_PART(1, 0, 0, 0, NULL),
							GEO_CLOSE_NODE(),
						GEO_CLOSE_NODE(),
						GEO_ANIMATED_PART(1, 132, 0, 0, NULL),
						GEO_ANIMATED_PART(1, 132, 0, 0, NULL),
						GEO_ANIMATED_PART(1, 78, 0, 79, NULL),
						GEO_OPEN_NODE(),
							GEO_ANIMATED_PART(5, 0, 0, 0, peach_000_offset_004_mesh),
							GEO_OPEN_NODE(),
								GEO_DISPLAY_LIST(5, peach_000_offset_005_skinned),
								GEO_ANIMATED_PART(5, 104, 0, 0, peach_000_offset_005_mesh),
								GEO_OPEN_NODE(),
									GEO_DISPLAY_LIST(5, peach_000_offset_006_skinned),
									GEO_ANIMATED_PART(5, 87, 0, 0, peach_000_offset_006_mesh),
								GEO_CLOSE_NODE(),
							GEO_CLOSE_NODE(),
							GEO_ANIMATED_PART(1, 0, 0, 0, NULL),
						GEO_CLOSE_NODE(),
						GEO_ANIMATED_PART(1, 77, 0, -81, NULL),
						GEO_OPEN_NODE(),
							GEO_ANIMATED_PART(5, 0, 0, 0, peach_000_offset_007_mesh),
							GEO_OPEN_NODE(),
								GEO_DISPLAY_LIST(5, peach_000_offset_008_skinned),
								GEO_ANIMATED_PART(5, 104, 0, 0, peach_000_offset_008_mesh),
								GEO_OPEN_NODE(),
									GEO_DISPLAY_LIST(5, peach_000_offset_009_skinned),
									GEO_ANIMATED_PART(5, 87, 0, 0, peach_000_offset_009_mesh),
								GEO_CLOSE_NODE(),
							GEO_CLOSE_NODE(),
							GEO_ANIMATED_PART(1, 0, 0, 0, NULL),
						GEO_CLOSE_NODE(),
					GEO_CLOSE_NODE(),
					GEO_ANIMATED_PART(5, 78, 0, 0, peach_002_offset_004_mesh),
					GEO_ANIMATED_PART(1, -23, -1, 0, NULL),
					GEO_OPEN_NODE(),
						GEO_ANIMATED_PART(1, 0, 0, 0, NULL),
					GEO_CLOSE_NODE(),
				GEO_CLOSE_NODE(),
			GEO_CLOSE_NODE(),
		GEO_CLOSE_NODE(),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout peach_001_switch_opt0_000_switch_opt4[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(1, peach_000_displaylist_mesh_mat_override_skin_0),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout peach_geo[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_SHADOW(0, 150, 100),
		GEO_OPEN_NODE(),
			GEO_SCALE(0, 16384),
			GEO_OPEN_NODE(),
				GEO_ASM(10, geo_update_layer_transparency),
				GEO_SWITCH_CASE(2, geo_switch_anim_state),
				GEO_OPEN_NODE(),
					GEO_NODE_START(),
					GEO_OPEN_NODE(),
						GEO_NODE_START(),
						GEO_OPEN_NODE(),
							GEO_ANIMATED_PART(1, 0, 0, 0, NULL),
							GEO_OPEN_NODE(),
								GEO_ANIMATED_PART(1, 0, 0, 0, peach_000_offset_mesh),
								GEO_OPEN_NODE(),
									GEO_ANIMATED_PART(1, 78, 0, 0, peach_000_offset_001_mesh),
									GEO_OPEN_NODE(),
										GEO_ANIMATED_PART(1, 132, 0, 0, NULL),
										GEO_OPEN_NODE(),
											GEO_SWITCH_CASE(8, geo_switch_peach_eyes),
											GEO_OPEN_NODE(),
												GEO_NODE_START(),
												GEO_OPEN_NODE(),
													GEO_DISPLAY_LIST(1, peach_000_displaylist_mesh),
												GEO_CLOSE_NODE(),
												GEO_BRANCH(1, peach_halfclosedeye),
												GEO_BRANCH(1, peach_quarterclosedeye),
												GEO_BRANCH(1, peach_closedeye),
												GEO_BRANCH(1, peach_001_switch_opt0_000_switch_opt4),
											GEO_CLOSE_NODE(),
											GEO_ANIMATED_PART(1, 38, -78, 0, NULL),
											GEO_OPEN_NODE(),
												GEO_ANIMATED_PART(1, 0, 0, 0, NULL),
											GEO_CLOSE_NODE(),
										GEO_CLOSE_NODE(),
										GEO_ANIMATED_PART(1, 132, 0, 0, NULL),
										GEO_ANIMATED_PART(1, 132, 0, 0, NULL),
										GEO_ANIMATED_PART(1, 78, 0, 79, NULL),
										GEO_OPEN_NODE(),
											GEO_ANIMATED_PART(1, 0, 0, 0, peach_000_offset_004_mesh),
											GEO_OPEN_NODE(),
												GEO_DISPLAY_LIST(1, peach_000_offset_005_skinned),
												GEO_ANIMATED_PART(1, 104, 0, 0, peach_000_offset_005_mesh),
												GEO_OPEN_NODE(),
													GEO_DISPLAY_LIST(1, peach_000_offset_006_skinned),
													GEO_ANIMATED_PART(1, 87, 0, 0, peach_000_offset_006_mesh),
												GEO_CLOSE_NODE(),
											GEO_CLOSE_NODE(),
											GEO_ANIMATED_PART(1, 0, 0, 0, NULL),
										GEO_CLOSE_NODE(),
										GEO_ANIMATED_PART(1, 77, 0, -81, NULL),
										GEO_OPEN_NODE(),
											GEO_ANIMATED_PART(1, 0, 0, 0, peach_000_offset_007_mesh),
											GEO_OPEN_NODE(),
												GEO_DISPLAY_LIST(1, peach_000_offset_008_skinned),
												GEO_ANIMATED_PART(1, 104, 0, 0, peach_000_offset_008_mesh),
												GEO_OPEN_NODE(),
													GEO_DISPLAY_LIST(1, peach_000_offset_009_skinned),
													GEO_ANIMATED_PART(1, 87, 0, 0, peach_000_offset_009_mesh),
												GEO_CLOSE_NODE(),
											GEO_CLOSE_NODE(),
											GEO_ANIMATED_PART(1, 0, 0, 0, NULL),
										GEO_CLOSE_NODE(),
									GEO_CLOSE_NODE(),
									GEO_ANIMATED_PART(1, 78, 0, 0, peach_002_offset_004_mesh),
									GEO_ANIMATED_PART(1, -23, -1, 0, NULL),
									GEO_OPEN_NODE(),
										GEO_ANIMATED_PART(1, 0, 0, 0, NULL),
									GEO_CLOSE_NODE(),
								GEO_CLOSE_NODE(),
							GEO_CLOSE_NODE(),
						GEO_CLOSE_NODE(),
					GEO_CLOSE_NODE(),
					GEO_BRANCH(1, peach_001_switch_opt1),
				GEO_CLOSE_NODE(),
			GEO_CLOSE_NODE(),
		GEO_CLOSE_NODE(),
		GEO_DISPLAY_LIST(0, peach_material_revert_render_settings),
		GEO_DISPLAY_LIST(1, peach_material_revert_render_settings),
		GEO_DISPLAY_LIST(2, peach_material_revert_render_settings),
		GEO_DISPLAY_LIST(3, peach_material_revert_render_settings),
		GEO_DISPLAY_LIST(4, peach_material_revert_render_settings),
		GEO_DISPLAY_LIST(5, peach_material_revert_render_settings),
		GEO_DISPLAY_LIST(6, peach_material_revert_render_settings),
		GEO_DISPLAY_LIST(7, peach_material_revert_render_settings),
	GEO_CLOSE_NODE(),
	GEO_END(),
};
