#include "src/game/envfx_snow.h"

const GeoLayout whomp_geo[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_CULLING_RADIUS(425532),
		GEO_OPEN_NODE(),
			GEO_TRANSLATE_NODE(0, 0, 0, -50),
			GEO_OPEN_NODE(),
				GEO_SHADOW(50, 180, 0),
				GEO_OPEN_NODE(),
					GEO_SCALE(0, 16384),
					GEO_OPEN_NODE(),
						GEO_ANIMATED_PART(1, 0, 0, 0, NULL),
						GEO_OPEN_NODE(),
							GEO_ANIMATED_PART(1, 0, 0, 0, whomp_000_offset_mesh),
							GEO_OPEN_NODE(),
								GEO_ANIMATED_PART(1, -12, 490, -5, NULL),
								GEO_OPEN_NODE(),
									GEO_ANIMATED_PART(1, 0, 0, 0, whomp_000_offset_002_mesh),
								GEO_CLOSE_NODE(),
								GEO_ANIMATED_PART(1, -18, -479, -5, NULL),
								GEO_OPEN_NODE(),
									GEO_ANIMATED_PART(1, 0, 0, 0, whomp_000_offset_003_mesh),
								GEO_CLOSE_NODE(),
								GEO_ANIMATED_PART(1, 1075, 570, 0, NULL),
								GEO_OPEN_NODE(),
									GEO_ANIMATED_PART(1, 0, 0, 0, whomp_000_offset_004_mesh),
									GEO_OPEN_NODE(),
										GEO_ANIMATED_PART(4, 400, 0, 0, NULL),
										GEO_OPEN_NODE(),
											GEO_BILLBOARD_WITH_PARAMS(0, 0, 0, 0),
											GEO_OPEN_NODE(),
												GEO_DISPLAY_LIST(4, NULL),
											GEO_CLOSE_NODE(),
										GEO_CLOSE_NODE(),
									GEO_CLOSE_NODE(),
								GEO_CLOSE_NODE(),
								GEO_ANIMATED_PART(1, 1068, -574, 0, NULL),
								GEO_OPEN_NODE(),
									GEO_ANIMATED_PART(1, 0, 0, 0, whomp_000_offset_006_mesh),
									GEO_OPEN_NODE(),
										GEO_ANIMATED_PART(4, 400, 0, 0, NULL),
										GEO_OPEN_NODE(),
											GEO_BILLBOARD_WITH_PARAMS(0, 0, 0, 0),
											GEO_OPEN_NODE(),
												GEO_DISPLAY_LIST(4, NULL),
											GEO_CLOSE_NODE(),
										GEO_CLOSE_NODE(),
									GEO_CLOSE_NODE(),
								GEO_CLOSE_NODE(),
							GEO_CLOSE_NODE(),
						GEO_CLOSE_NODE(),
					GEO_CLOSE_NODE(),
				GEO_CLOSE_NODE(),
			GEO_CLOSE_NODE(),
		GEO_CLOSE_NODE(),
		GEO_DISPLAY_LIST(0, whomp_material_revert_render_settings),
		GEO_DISPLAY_LIST(1, whomp_material_revert_render_settings),
		GEO_DISPLAY_LIST(2, whomp_material_revert_render_settings),
		GEO_DISPLAY_LIST(3, whomp_material_revert_render_settings),
		GEO_DISPLAY_LIST(4, whomp_material_revert_render_settings),
		GEO_DISPLAY_LIST(5, whomp_material_revert_render_settings),
		GEO_DISPLAY_LIST(6, whomp_material_revert_render_settings),
		GEO_DISPLAY_LIST(7, whomp_material_revert_render_settings),
	GEO_CLOSE_NODE(),
	GEO_END(),
};
