extern const GeoLayout wooden_signpost_geo[];
extern u8 wooden_signpost_signbake_rgba32[];
extern u8 wooden_signpost_exclamationpoint_rgba32[];
extern Vtx wooden_signpost_000_displaylist_mesh_layer_1_vtx_0[61];
extern Gfx wooden_signpost_000_displaylist_mesh_layer_1_tri_0[];
extern Vtx wooden_signpost_001_displaylist_mesh_layer_1_vtx_0[581];
extern Gfx wooden_signpost_001_displaylist_mesh_layer_1_tri_0[];
extern Vtx wooden_signpost_001_displaylist_mesh_layer_1_vtx_1[39];
extern Gfx wooden_signpost_001_displaylist_mesh_layer_1_tri_1[];
extern Gfx mat_wooden_signpost_sign_wood[];
extern Gfx mat_wooden_signpost_sign_text[];
extern Gfx wooden_signpost_000_displaylist_mesh_layer_1[];
extern Gfx wooden_signpost_001_displaylist_mesh_layer_1[];
extern Gfx wooden_signpost_material_revert_render_settings[];
