#include "src/game/envfx_snow.h"

const GeoLayout toad_geo[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_CULLING_RADIUS(212766),
		GEO_OPEN_NODE(),
			GEO_SHADOW(0, 150, 100),
			GEO_OPEN_NODE(),
				GEO_SCALE(0, 16384),
				GEO_OPEN_NODE(),
					GEO_ASM(10, geo_update_layer_transparency),
					GEO_SWITCH_CASE(2, geo_switch_anim_state),
					GEO_OPEN_NODE(),
						GEO_NODE_START(),
						GEO_OPEN_NODE(),
							GEO_NODE_START(),
							GEO_OPEN_NODE(),
								GEO_ANIMATED_PART(1, 0, 0, 0, NULL),
								GEO_OPEN_NODE(),
									GEO_ANIMATED_PART(1, 0, 0, 0, NULL),
									GEO_OPEN_NODE(),
										GEO_ANIMATED_PART(1, 114, 0, 0, NULL),
										GEO_OPEN_NODE(),
											GEO_ANIMATED_PART(1, 126, -37, 0, toad_000_offset_002_mesh),
										GEO_CLOSE_NODE(),
										GEO_ANIMATED_PART(1, 25, 8, 0, NULL),
										GEO_ANIMATED_PART(1, 58, 8, 0, toad_003_offset_mesh),
										GEO_ANIMATED_PART(1, 4, -15, 38, NULL),
										GEO_OPEN_NODE(),
											GEO_ANIMATED_PART(1, 0, 0, 0, NULL),
											GEO_OPEN_NODE(),
												GEO_ANIMATED_PART(1, 37, 0, 0, NULL),
												GEO_OPEN_NODE(),
													GEO_ANIMATED_PART(1, 9, -25, 3, toad_000_offset_005_mesh),
												GEO_CLOSE_NODE(),
											GEO_CLOSE_NODE(),
										GEO_CLOSE_NODE(),
										GEO_ANIMATED_PART(1, 4, -15, -38, NULL),
										GEO_OPEN_NODE(),
											GEO_ANIMATED_PART(1, 0, 0, 0, NULL),
											GEO_OPEN_NODE(),
												GEO_ANIMATED_PART(1, 37, 0, 0, NULL),
												GEO_OPEN_NODE(),
													GEO_ANIMATED_PART(1, 9, -25, -3, toad_000_offset_008_mesh),
												GEO_CLOSE_NODE(),
											GEO_CLOSE_NODE(),
										GEO_CLOSE_NODE(),
										GEO_ANIMATED_PART(1, 93, 6, 52, NULL),
										GEO_OPEN_NODE(),
											GEO_ANIMATED_PART(1, 0, 0, 0, NULL),
											GEO_OPEN_NODE(),
												GEO_ANIMATED_PART(1, 17, 0, 4, toad_000_offset_010_mesh),
											GEO_CLOSE_NODE(),
										GEO_CLOSE_NODE(),
										GEO_ANIMATED_PART(1, 93, 6, -52, NULL),
										GEO_OPEN_NODE(),
											GEO_ANIMATED_PART(1, 0, 0, 0, NULL),
											GEO_OPEN_NODE(),
												GEO_ANIMATED_PART(1, 17, 0, -4, toad_000_offset_012_mesh),
											GEO_CLOSE_NODE(),
										GEO_CLOSE_NODE(),
									GEO_CLOSE_NODE(),
								GEO_CLOSE_NODE(),
							GEO_CLOSE_NODE(),
						GEO_CLOSE_NODE(),
					GEO_CLOSE_NODE(),
				GEO_CLOSE_NODE(),
			GEO_CLOSE_NODE(),
		GEO_CLOSE_NODE(),
		GEO_DISPLAY_LIST(0, toad_material_revert_render_settings),
		GEO_DISPLAY_LIST(1, toad_material_revert_render_settings),
		GEO_DISPLAY_LIST(2, toad_material_revert_render_settings),
		GEO_DISPLAY_LIST(3, toad_material_revert_render_settings),
		GEO_DISPLAY_LIST(4, toad_material_revert_render_settings),
		GEO_DISPLAY_LIST(5, toad_material_revert_render_settings),
		GEO_DISPLAY_LIST(6, toad_material_revert_render_settings),
		GEO_DISPLAY_LIST(7, toad_material_revert_render_settings),
	GEO_CLOSE_NODE(),
	GEO_END(),
};
