#include "src/game/envfx_snow.h"

const GeoLayout mr_i_eyeball_closed2[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(4, mr_i_eyeball_000_switch_closed_mesh),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout mr_i_eyeball_mostlyopen2[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(4, mr_i_eyeball_000_switch_mostlyopen_mesh),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout mr_i_eyeball_mostlyclosed2[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(4, mr_i_eyeball_000_switch_mostlyclosed_mesh),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout mr_i_eyeball_open2[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(4, mr_i_eyeball_000_displaylist_mesh),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout mr_i_geo[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_NODE_START(),
		GEO_OPEN_NODE(),
			GEO_SWITCH_CASE(20, geo_switch_anim_state),
			GEO_OPEN_NODE(),
				GEO_NODE_START(),
				GEO_OPEN_NODE(),
					GEO_DISPLAY_LIST(4, mr_i_eyeball_000_displaylist_mesh),
				GEO_CLOSE_NODE(),
				GEO_BRANCH(1, mr_i_eyeball_open2),
				GEO_BRANCH(1, mr_i_eyeball_mostlyopen2),
				GEO_BRANCH(1, mr_i_eyeball_mostlyclosed2),
				GEO_BRANCH(1, mr_i_eyeball_closed2),
				GEO_BRANCH(1, mr_i_eyeball_mostlyclosed2),
				GEO_BRANCH(1, mr_i_eyeball_mostlyopen2),
				GEO_BRANCH(1, mr_i_eyeball_open2),
				GEO_BRANCH(1, mr_i_eyeball_open2),
				GEO_BRANCH(1, mr_i_eyeball_open2),
				GEO_BRANCH(1, mr_i_eyeball_mostlyopen2),
				GEO_BRANCH(1, mr_i_eyeball_mostlyclosed2),
				GEO_BRANCH(1, mr_i_eyeball_closed2),
				GEO_BRANCH(1, mr_i_eyeball_mostlyclosed2),
				GEO_BRANCH(1, mr_i_eyeball_mostlyopen2),
				GEO_BRANCH(1, mr_i_eyeball_open2),
				GEO_BRANCH(1, mr_i_eyeball_open2),
				GEO_BRANCH(1, mr_i_eyeball_open2),
				GEO_BRANCH(1, mr_i_eyeball_open2),
				GEO_BRANCH(1, mr_i_eyeball_open2),
				GEO_BRANCH(1, mr_i_eyeball_open2),
			GEO_CLOSE_NODE(),
		GEO_CLOSE_NODE(),
		GEO_DISPLAY_LIST(0, mr_i_eyeball_material_revert_render_settings),
		GEO_DISPLAY_LIST(1, mr_i_eyeball_material_revert_render_settings),
		GEO_DISPLAY_LIST(2, mr_i_eyeball_material_revert_render_settings),
		GEO_DISPLAY_LIST(3, mr_i_eyeball_material_revert_render_settings),
		GEO_DISPLAY_LIST(4, mr_i_eyeball_material_revert_render_settings),
		GEO_DISPLAY_LIST(5, mr_i_eyeball_material_revert_render_settings),
		GEO_DISPLAY_LIST(6, mr_i_eyeball_material_revert_render_settings),
		GEO_DISPLAY_LIST(7, mr_i_eyeball_material_revert_render_settings),
	GEO_CLOSE_NODE(),
	GEO_END(),
};
