#include "src/game/envfx_snow.h"

const GeoLayout spiny_ball_geo[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_SHADOW(0, 150, 100),
		GEO_OPEN_NODE(),
			GEO_SCALE(0, 16384),
			GEO_OPEN_NODE(),
				GEO_ANIMATED_PART(1, -18, -34, 10, spiny_egg_root_mesh),
				GEO_OPEN_NODE(),
					GEO_ANIMATED_PART(1, 0, 0, 0, NULL),
					GEO_ANIMATED_PART(1, 0, 0, 0, NULL),
					GEO_ANIMATED_PART(1, 0, 0, 0, NULL),
					GEO_ANIMATED_PART(1, 0, 0, 0, NULL),
					GEO_ANIMATED_PART(1, 0, 0, 0, NULL),
					GEO_ANIMATED_PART(1, 0, 0, 0, NULL),
					GEO_ANIMATED_PART(1, 0, 0, 0, NULL),
					GEO_ANIMATED_PART(1, 0, 0, 0, NULL),
				GEO_CLOSE_NODE(),
			GEO_CLOSE_NODE(),
		GEO_CLOSE_NODE(),
		GEO_DISPLAY_LIST(0, spiny_egg_material_revert_render_settings),
		GEO_DISPLAY_LIST(1, spiny_egg_material_revert_render_settings),
		GEO_DISPLAY_LIST(2, spiny_egg_material_revert_render_settings),
		GEO_DISPLAY_LIST(3, spiny_egg_material_revert_render_settings),
		GEO_DISPLAY_LIST(4, spiny_egg_material_revert_render_settings),
		GEO_DISPLAY_LIST(5, spiny_egg_material_revert_render_settings),
		GEO_DISPLAY_LIST(6, spiny_egg_material_revert_render_settings),
		GEO_DISPLAY_LIST(7, spiny_egg_material_revert_render_settings),
	GEO_CLOSE_NODE(),
	GEO_END(),
};
