#include "src/game/envfx_snow.h"

const GeoLayout sushi_geo[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_CULLING_RADIUS(170213),
		GEO_OPEN_NODE(),
			GEO_SCALE(0, 16384),
			GEO_OPEN_NODE(),
				GEO_ANIMATED_PART(1, 0, 0, 0, NULL),
				GEO_OPEN_NODE(),
					GEO_ANIMATED_PART(1, 0, 0, 0, sushi_000_offset_mesh),
					GEO_OPEN_NODE(),
						GEO_ASM(0, geo_update_body_rot_from_parent),
						GEO_DISPLAY_LIST(1, sushi_000_offset_001_skinned),
						GEO_ANIMATED_PART(1, 201, 0, 0, sushi_000_offset_001_mesh),
						GEO_OPEN_NODE(),
							GEO_DISPLAY_LIST(1, sushi_000_offset_002_skinned),
							GEO_ANIMATED_PART(1, 415, 0, 0, sushi_000_offset_002_mesh),
							GEO_OPEN_NODE(),
								GEO_DISPLAY_LIST(1, sushi_000_offset_003_skinned),
								GEO_ANIMATED_PART(1, 486, 0, 0, sushi_000_offset_003_mesh),
							GEO_CLOSE_NODE(),
						GEO_CLOSE_NODE(),
					GEO_CLOSE_NODE(),
					GEO_ANIMATED_PART(4, 0, 0, 0, NULL),
					GEO_ANIMATED_PART(4, 0, 0, 0, NULL),
				GEO_CLOSE_NODE(),
			GEO_CLOSE_NODE(),
		GEO_CLOSE_NODE(),
		GEO_DISPLAY_LIST(0, sushi_material_revert_render_settings),
		GEO_DISPLAY_LIST(1, sushi_material_revert_render_settings),
		GEO_DISPLAY_LIST(2, sushi_material_revert_render_settings),
		GEO_DISPLAY_LIST(3, sushi_material_revert_render_settings),
		GEO_DISPLAY_LIST(4, sushi_material_revert_render_settings),
		GEO_DISPLAY_LIST(5, sushi_material_revert_render_settings),
		GEO_DISPLAY_LIST(6, sushi_material_revert_render_settings),
		GEO_DISPLAY_LIST(7, sushi_material_revert_render_settings),
	GEO_CLOSE_NODE(),
	GEO_END(),
};
