#include "src/game/envfx_snow.h"

const GeoLayout koopa_with_shell_geo[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_SHADOW(0, 155, 100),
		GEO_OPEN_NODE(),
			GEO_SCALE(0, 16384),
			GEO_OPEN_NODE(),
				GEO_ANIMATED_PART(1, 0, 0, 0, NULL),
				GEO_OPEN_NODE(),
					GEO_ANIMATED_PART(1, 0, 0, 0, koopa_000_offset_mesh),
					GEO_OPEN_NODE(),
						GEO_SWITCH_CASE(2, geo_switch_anim_state),
						GEO_OPEN_NODE(),
							GEO_NODE_START(),
							GEO_OPEN_NODE(),
								GEO_ANIMATED_PART(1, 114, 0, 0, koopa_000_offset_001_mesh),
							GEO_CLOSE_NODE(),
						GEO_CLOSE_NODE(),
						GEO_ANIMATED_PART(1, -29, 39, 52, NULL),
						GEO_OPEN_NODE(),
							GEO_ANIMATED_PART(1, 0, 0, 0, koopa_000_offset_002_mesh),
							GEO_OPEN_NODE(),
								GEO_ANIMATED_PART(1, 60, 0, 0, koopa_000_offset_003_mesh),
							GEO_CLOSE_NODE(),
						GEO_CLOSE_NODE(),
						GEO_ANIMATED_PART(1, -29, 39, -51, NULL),
						GEO_OPEN_NODE(),
							GEO_ANIMATED_PART(1, 0, 0, 0, koopa_000_offset_004_mesh),
							GEO_OPEN_NODE(),
								GEO_ANIMATED_PART(1, 60, 0, 0, koopa_000_offset_005_mesh),
							GEO_CLOSE_NODE(),
						GEO_CLOSE_NODE(),
						GEO_ANIMATED_PART(1, 55, 25, -40, NULL),
						GEO_OPEN_NODE(),
							GEO_ANIMATED_PART(1, 0, 0, 0, koopa_000_offset_006_mesh),
							GEO_OPEN_NODE(),
								GEO_ANIMATED_PART(1, 54, 0, 0, koopa_000_offset_007_mesh),
							GEO_CLOSE_NODE(),
						GEO_CLOSE_NODE(),
						GEO_ANIMATED_PART(1, 55, 25, 42, NULL),
						GEO_OPEN_NODE(),
							GEO_ANIMATED_PART(1, 0, 0, 0, koopa_000_offset_008_mesh),
							GEO_OPEN_NODE(),
								GEO_ANIMATED_PART(1, 54, 0, 0, koopa_000_offset_009_mesh),
							GEO_CLOSE_NODE(),
						GEO_CLOSE_NODE(),
					GEO_CLOSE_NODE(),
				GEO_CLOSE_NODE(),
			GEO_CLOSE_NODE(),
		GEO_CLOSE_NODE(),
		GEO_DISPLAY_LIST(0, koopa_material_revert_render_settings),
		GEO_DISPLAY_LIST(1, koopa_material_revert_render_settings),
		GEO_DISPLAY_LIST(2, koopa_material_revert_render_settings),
		GEO_DISPLAY_LIST(3, koopa_material_revert_render_settings),
		GEO_DISPLAY_LIST(4, koopa_material_revert_render_settings),
		GEO_DISPLAY_LIST(5, koopa_material_revert_render_settings),
		GEO_DISPLAY_LIST(6, koopa_material_revert_render_settings),
		GEO_DISPLAY_LIST(7, koopa_material_revert_render_settings),
	GEO_CLOSE_NODE(),
	GEO_END(),
};


const GeoLayout koopa_without_shell_geo[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_SHADOW(0, 155, 100),
		GEO_OPEN_NODE(),
			GEO_SCALE(0, 16384),
			GEO_OPEN_NODE(),
				GEO_ANIMATED_PART(1, 0, 0, 0, NULL),
				GEO_OPEN_NODE(),
					GEO_ANIMATED_PART(1, 0, 0, 0, koopa_without_shell_000_offset_mesh),
					GEO_OPEN_NODE(),
						GEO_SWITCH_CASE(2, geo_switch_anim_state),
						GEO_OPEN_NODE(),
							GEO_NODE_START(),
							GEO_OPEN_NODE(),
								GEO_ANIMATED_PART(1, 114, 0, 0, koopa_without_shell_000_offset_001_mesh),
							GEO_CLOSE_NODE(),
						GEO_CLOSE_NODE(),
						GEO_ANIMATED_PART(1, -29, 39, 41, NULL),
						GEO_OPEN_NODE(),
							GEO_ANIMATED_PART(1, 0, 0, 0, koopa_without_shell_000_offset_002_mesh),
							GEO_OPEN_NODE(),
								GEO_ANIMATED_PART(1, 60, 0, 0, koopa_without_shell_000_offset_003_mesh),
							GEO_CLOSE_NODE(),
						GEO_CLOSE_NODE(),
						GEO_ANIMATED_PART(1, -29, 39, -39, NULL),
						GEO_OPEN_NODE(),
							GEO_ANIMATED_PART(1, 0, 0, 0, koopa_without_shell_000_offset_004_mesh),
							GEO_OPEN_NODE(),
								GEO_ANIMATED_PART(1, 60, 0, 0, koopa_without_shell_000_offset_005_mesh),
							GEO_CLOSE_NODE(),
						GEO_CLOSE_NODE(),
						GEO_ANIMATED_PART(1, 55, 25, -40, NULL),
						GEO_OPEN_NODE(),
							GEO_ANIMATED_PART(1, 0, 0, 0, koopa_without_shell_000_offset_006_mesh),
							GEO_OPEN_NODE(),
								GEO_ANIMATED_PART(1, 54, 0, 0, koopa_without_shell_000_offset_007_mesh),
							GEO_CLOSE_NODE(),
						GEO_CLOSE_NODE(),
						GEO_ANIMATED_PART(1, 55, 25, 42, NULL),
						GEO_OPEN_NODE(),
							GEO_ANIMATED_PART(1, 0, 0, 0, koopa_without_shell_000_offset_008_mesh),
							GEO_OPEN_NODE(),
								GEO_ANIMATED_PART(1, 54, 0, 0, koopa_without_shell_000_offset_009_mesh),
							GEO_CLOSE_NODE(),
						GEO_CLOSE_NODE(),
					GEO_CLOSE_NODE(),
				GEO_CLOSE_NODE(),
			GEO_CLOSE_NODE(),
		GEO_CLOSE_NODE(),
		GEO_DISPLAY_LIST(0, koopa_without_shell_material_revert_render_settings),
		GEO_DISPLAY_LIST(1, koopa_without_shell_material_revert_render_settings),
		GEO_DISPLAY_LIST(2, koopa_without_shell_material_revert_render_settings),
		GEO_DISPLAY_LIST(3, koopa_without_shell_material_revert_render_settings),
		GEO_DISPLAY_LIST(4, koopa_without_shell_material_revert_render_settings),
		GEO_DISPLAY_LIST(5, koopa_without_shell_material_revert_render_settings),
		GEO_DISPLAY_LIST(6, koopa_without_shell_material_revert_render_settings),
		GEO_DISPLAY_LIST(7, koopa_without_shell_material_revert_render_settings),
	GEO_CLOSE_NODE(),
	GEO_END(),
};
