#include "src/game/envfx_snow.h"

const GeoLayout swoop_geo[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_SHADOW(0, 150, 100),
		GEO_OPEN_NODE(),
			GEO_SCALE(0, 16384),
			GEO_OPEN_NODE(),
				GEO_ANIMATED_PART(1, 0, 0, 0, NULL),
				GEO_OPEN_NODE(),
					GEO_ANIMATED_PART(1, 0, 0, 0, NULL),
					GEO_OPEN_NODE(),
						GEO_BILLBOARD_WITH_PARAMS(0, 0, 0, 0),
						GEO_OPEN_NODE(),
							GEO_DISPLAY_LIST(4, NULL),
						GEO_CLOSE_NODE(),
						GEO_ANIMATED_PART(1, 54, 0, 0, swoop_000_offset_001_mesh),
						GEO_ANIMATED_PART(1, 54, 0, 0, NULL),
						GEO_ANIMATED_PART(1, -150, -48, 0, NULL),
						GEO_OPEN_NODE(),
							GEO_ANIMATED_PART(4, 0, 0, 0, swoop_000_offset_002_mesh),
						GEO_CLOSE_NODE(),
						GEO_ANIMATED_PART(1, -150, -48, 0, NULL),
						GEO_OPEN_NODE(),
							GEO_ANIMATED_PART(4, 0, 0, 0, swoop_000_offset_003_mesh),
						GEO_CLOSE_NODE(),
					GEO_CLOSE_NODE(),
				GEO_CLOSE_NODE(),
			GEO_CLOSE_NODE(),
		GEO_CLOSE_NODE(),
		GEO_DISPLAY_LIST(0, swoop_material_revert_render_settings),
		GEO_DISPLAY_LIST(1, swoop_material_revert_render_settings),
		GEO_DISPLAY_LIST(2, swoop_material_revert_render_settings),
		GEO_DISPLAY_LIST(3, swoop_material_revert_render_settings),
		GEO_DISPLAY_LIST(4, swoop_material_revert_render_settings),
		GEO_DISPLAY_LIST(5, swoop_material_revert_render_settings),
		GEO_DISPLAY_LIST(6, swoop_material_revert_render_settings),
		GEO_DISPLAY_LIST(7, swoop_material_revert_render_settings),
	GEO_CLOSE_NODE(),
	GEO_END(),
};
