#include "src/game/envfx_snow.h"

const GeoLayout scuttlebug_geo[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_SHADOW(0, 150, 100),
		GEO_OPEN_NODE(),
			GEO_SCALE(0, 16384),
			GEO_OPEN_NODE(),
				GEO_ANIMATED_PART(1, 0, 0, 0, NULL),
				GEO_OPEN_NODE(),
					GEO_ANIMATED_PART(1, 0, -29, 0, NULL),
					GEO_OPEN_NODE(),
						GEO_ANIMATED_PART(1, -1, 113, 112, NULL),
						GEO_OPEN_NODE(),
							GEO_ANIMATED_PART(1, 0, 0, 0, NULL),
							GEO_OPEN_NODE(),
								GEO_ANIMATED_PART(1, 198, 0, 0, NULL),
								GEO_OPEN_NODE(),
									GEO_ANIMATED_PART(1, 195, 0, 0, NULL),
									GEO_OPEN_NODE(),
										GEO_ANIMATED_PART(4, 0, 0, 0, scuttlebug_000_offset_005_mesh),
									GEO_CLOSE_NODE(),
									GEO_ANIMATED_PART(4, 0, 0, 0, scuttlebug_002_offset_mesh),
								GEO_CLOSE_NODE(),
								GEO_ANIMATED_PART(4, 0, 0, 0, scuttlebug_002_offset_001_mesh),
							GEO_CLOSE_NODE(),
						GEO_CLOSE_NODE(),
						GEO_ANIMATED_PART(1, -1, 109, -116, NULL),
						GEO_OPEN_NODE(),
							GEO_ANIMATED_PART(1, 0, 0, 0, NULL),
							GEO_OPEN_NODE(),
								GEO_ANIMATED_PART(1, 198, 0, 0, NULL),
								GEO_OPEN_NODE(),
									GEO_ANIMATED_PART(1, 195, 0, 0, NULL),
									GEO_OPEN_NODE(),
										GEO_ANIMATED_PART(4, 0, 0, 0, scuttlebug_000_offset_009_mesh),
									GEO_CLOSE_NODE(),
									GEO_ANIMATED_PART(4, 0, 0, 0, scuttlebug_002_offset_003_mesh),
								GEO_CLOSE_NODE(),
								GEO_ANIMATED_PART(4, 0, 0, 0, scuttlebug_002_offset_004_mesh),
							GEO_CLOSE_NODE(),
						GEO_CLOSE_NODE(),
						GEO_ANIMATED_PART(1, 0, 0, 0, NULL),
						GEO_OPEN_NODE(),
									GEO_SCALE(0x00, 220000),
										//GEO_BILLBOARD_WITH_PARAMS(0, 0, 0, 0),
							GEO_OPEN_NODE(),
								GEO_DISPLAY_LIST(4, scuttlebug_000_displaylist_mesh),
							GEO_CLOSE_NODE(),
						GEO_CLOSE_NODE(),
						GEO_ANIMATED_PART(1, -29, -57, 28, NULL),
						GEO_OPEN_NODE(),
							GEO_ANIMATED_PART(1, 0, 0, 0, NULL),
							GEO_OPEN_NODE(),
								GEO_ANIMATED_PART(1, 158, 0, 0, NULL),
								GEO_OPEN_NODE(),
									GEO_ANIMATED_PART(1, 0, 0, 0, NULL),
									GEO_OPEN_NODE(),
									GEO_SCALE(0x00, 220000),
										//GEO_BILLBOARD_WITH_PARAMS(0, 0, 0, 0),
										GEO_OPEN_NODE(),
											GEO_DISPLAY_LIST(4, scuttlebug_000_displaylist_001_mesh),
										GEO_CLOSE_NODE(),
									GEO_CLOSE_NODE(),
									GEO_ANIMATED_PART(4, 0, 0, 0, NULL),
								GEO_CLOSE_NODE(),
							GEO_CLOSE_NODE(),
						GEO_CLOSE_NODE(),
						GEO_ANIMATED_PART(1, -29, 55, 28, NULL),
						GEO_OPEN_NODE(),
							GEO_ANIMATED_PART(1, 0, 0, 0, NULL),
							GEO_OPEN_NODE(),
								GEO_ANIMATED_PART(1, 157, 0, 0, NULL),
								GEO_OPEN_NODE(),
									GEO_ANIMATED_PART(1, 0, 0, 0, NULL),
									GEO_OPEN_NODE(),
									GEO_SCALE(0x00, 220000),
										//GEO_BILLBOARD_WITH_PARAMS(0, 0, 0, 0),
										GEO_OPEN_NODE(),
											GEO_DISPLAY_LIST(4, scuttlebug_000_displaylist_002_mesh),
										GEO_CLOSE_NODE(),
									GEO_CLOSE_NODE(),
									GEO_ANIMATED_PART(4, 0, 0, 0, NULL),
								GEO_CLOSE_NODE(),
							GEO_CLOSE_NODE(),
						GEO_CLOSE_NODE(),
						GEO_ANIMATED_PART(1, -1, -116, -111, NULL),
						GEO_OPEN_NODE(),
							GEO_ANIMATED_PART(1, 0, 0, 0, NULL),
							GEO_OPEN_NODE(),
								GEO_ANIMATED_PART(1, 198, 0, 0, NULL),
								GEO_OPEN_NODE(),
									GEO_ANIMATED_PART(1, 195, 0, 0, NULL),
									GEO_OPEN_NODE(),
										GEO_ANIMATED_PART(4, 0, 0, 0, scuttlebug_000_offset_019_mesh),
									GEO_CLOSE_NODE(),
									GEO_ANIMATED_PART(4, 0, 0, 0, scuttlebug_002_offset_007_mesh),
								GEO_CLOSE_NODE(),
								GEO_ANIMATED_PART(4, 0, 0, 0, scuttlebug_002_offset_008_mesh),
							GEO_CLOSE_NODE(),
						GEO_CLOSE_NODE(),
						GEO_ANIMATED_PART(1, -1, -116, 112, NULL),
						GEO_OPEN_NODE(),
							GEO_ANIMATED_PART(1, 0, 0, 0, NULL),
							GEO_OPEN_NODE(),
								GEO_ANIMATED_PART(1, 195, 0, 0, NULL),
								GEO_OPEN_NODE(),
									GEO_ANIMATED_PART(1, 199, 0, 0, NULL),
									GEO_OPEN_NODE(),
										GEO_ANIMATED_PART(4, 0, 0, 0, scuttlebug_000_offset_023_mesh),
									GEO_CLOSE_NODE(),
									GEO_ANIMATED_PART(4, 0, 0, 0, scuttlebug_002_offset_009_mesh),
								GEO_CLOSE_NODE(),
								GEO_ANIMATED_PART(4, 0, 0, 0, scuttlebug_002_offset_010_mesh),
							GEO_CLOSE_NODE(),
						GEO_CLOSE_NODE(),
						GEO_ANIMATED_PART(1, 0, 0, 0, scuttlebug_014_offset_mesh),
					GEO_CLOSE_NODE(),
				GEO_CLOSE_NODE(),
			GEO_CLOSE_NODE(),
		GEO_CLOSE_NODE(),
		GEO_DISPLAY_LIST(0, scuttlebug_material_revert_render_settings),
		GEO_DISPLAY_LIST(1, scuttlebug_material_revert_render_settings),
		GEO_DISPLAY_LIST(2, scuttlebug_material_revert_render_settings),
		GEO_DISPLAY_LIST(3, scuttlebug_material_revert_render_settings),
		GEO_DISPLAY_LIST(4, scuttlebug_material_revert_render_settings),
		GEO_DISPLAY_LIST(5, scuttlebug_material_revert_render_settings),
		GEO_DISPLAY_LIST(6, scuttlebug_material_revert_render_settings),
		GEO_DISPLAY_LIST(7, scuttlebug_material_revert_render_settings),
	GEO_CLOSE_NODE(),
	GEO_END(),
};
