#include "src/game/envfx_snow.h"

const GeoLayout boo_key_geo[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_SCALE(0, 16384),
		GEO_OPEN_NODE(),
			GEO_ANIMATED_PART(1, 0, 0, 0, NULL),
			GEO_OPEN_NODE(),
				GEO_ANIMATED_PART(1, 0, 0, 0, NULL),
				GEO_OPEN_NODE(),
					GEO_OPEN_NODE(),
						GEO_DISPLAY_LIST(1, boo_key_000_displaylist_mesh),
					GEO_CLOSE_NODE(),
				GEO_CLOSE_NODE(),
			GEO_CLOSE_NODE(),
		GEO_CLOSE_NODE(),
		GEO_DISPLAY_LIST(0, boo_key_material_revert_render_settings),
		GEO_DISPLAY_LIST(1, boo_key_material_revert_render_settings),
		GEO_DISPLAY_LIST(2, boo_key_material_revert_render_settings),
		GEO_DISPLAY_LIST(3, boo_key_material_revert_render_settings),
		GEO_DISPLAY_LIST(4, boo_key_material_revert_render_settings),
		GEO_DISPLAY_LIST(5, boo_key_material_revert_render_settings),
		GEO_DISPLAY_LIST(6, boo_key_material_revert_render_settings),
		GEO_DISPLAY_LIST(7, boo_key_material_revert_render_settings),
	GEO_CLOSE_NODE(),
	GEO_END(),
};
